feat(videobanner): allow using html tag in title and description of videobanner
MegafonWebLab/megafon-ui pull request #1004
Opened 2022-10-03 07:36 UTC by Kolesatost

List of allowed html-tag: "<br>, &nbsp, <b>, <font color>, <a href>"

2022-10-03 07:46 UTC, IGoRFonin commented
В названии коммита должен указываться компонент, посмотри как в других

2022-10-03 09:55 UTC, Kolesatost commented
> В названии коммита должен указываться компонент, посмотри как в других

исправил

2022-10-03 11:01 UTC, myfka requested changes

2022-10-03 11:01 UTC, myfka commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +            <> </>
Пробел - очень неочевидный символ в данном случае
```
<>{String.fromCharCode(160)}</>
```

2022-10-03 11:01 UTC, myfka commented on packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.example.mdx
> +В свойстве content в свойствах title и description поддерживаются некоторые HTML-теги: "<br>, &nbsp, <b>, <font color>, <a href>".
Строго говоря, `&nbsp` - не тэг, а спецсимвол

2022-10-04 10:58 UTC, myfka approved these changes

2022-10-04 11:17 UTC, merged