feat(select): add new props useShortListItems
MegafonWebLab/megafon-ui pull request #1008
Opened 2022-10-05 13:24 UTC by bashmakovartur

2022-10-06 08:42 UTC, n-ilyin commented on packages/ui-core/src/components/Select/Select.less
> +        &_list-inner-short {
Нет смысла в названии модификатора повторять название элемента, достаточно &__list-inner_short

2022-10-06 12:50 UTC, svetogor requested changes

2022-10-06 12:50 UTC, svetogor commented on packages/ui-core/src/components/Select/Select.tsx
> +    useShortListItems?: boolean;
предлагаю переименовать проп:
- отказаться от префикса `use`, так как он наводит на мысли, что это может быть хуком
- убрать слово `Items`, потому что мы оперируем термином `list` внутри компонента

таким образом проп может называться `shortList`, например

2022-10-07 11:34 UTC, svetogor approved these changes

2022-10-10 09:57 UTC, merged