7695 add search component
MegafonWebLab/megafon-ui pull request #312
Opened 2020-08-11 16:40 UTC by fruktovoe-ragu

2020-09-14 18:54 UTC, jekatigr requested changes

2020-09-14 18:56 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.docz.tsx
> +            {children({ onSubmit: handleSubmit })}
```suggestion
            {children({ onSubmit: setValue })}
```
И метод handleSubmit выше вообще не нужен.

2020-09-14 18:59 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.mdx
> +        return (
```suggestion

        return (
```

2020-09-14 19:00 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.test.tsx
> +            const listItemActive = 'mfui-search__list-item_active';
Может и тут лучше через cn?

2020-09-14 19:00 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +import {useCallback, useState, useRef, useEffect} from 'react';
```suggestion
import { useCallback, useState, useRef, useEffect } from 'react';
```

2020-09-14 19:04 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +    }, [searchQuery]);
Кажется, onSubmit не хватает в зависимостях.

2020-09-14 19:06 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +    const handleFieldFocus: React.EventHandler<React.FocusEvent<HTMLInputElement>> =
```suggestion
    const handleFieldFocusToggle: React.EventHandler<React.FocusEvent<HTMLInputElement>> =
```

2020-09-14 19:07 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +    const handleKeyDown: React.EventHandler<React.KeyboardEvent<HTMLInputElement>> =
А все эти стремные типы у переменных для функций случайно ts'ом автоматически не выводятся? Если их убрать, все сломается?

2020-09-14 19:08 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +        }, [activeIndex, setActiveIndex, handleSearchSubmit]);
Тоже не все зависимости, handleItemSubmit не хватает.

2020-09-14 19:08 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +        wrapper.find(SelectItem).find({ title: 'test2' }).simulate('mouseDown');
А для чего был изменен тип события?

2020-09-14 20:04 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +                                onMouseDown={handleSelectSubmit(i)}
В селекте чтобы не создавать на каждый рендер по функции использовался activeIndex, лучше тут поступить также.

2020-09-15 12:46 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Search/Search.mdx
> +        return (
mdx не приемлет строковые отступы

2020-09-15 13:39 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Select/Select.test.tsx
> +        wrapper.find(SelectItem).find({ title: 'test2' }).simulate('mouseDown');
уже не вспомню мотив. Но теперь это не имеет значения, так как этот тест уже не существует. И SelectItem мы удалили.

2020-09-17 14:07 UTC, jekatigr requested changes

2020-09-17 14:07 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.test.tsx
> +const props: ISearchProps = {
Не все пропсы представлены.

2020-09-17 14:07 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.mdx
> +<Props of={Search} />
Нужно проверить, все ли пропсы есть в примерах.

2020-09-22 12:06 UTC, jekatigr requested changes

2020-09-22 12:06 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
>      /** Array of objects to be used for options rendering */
```suggestion
    /** Array of strings to be used for options rendering */
```

2020-09-22 12:06 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +            {!!filteredItems.length &&
В этом компоненте не нужна фильтрация внутри, т.к. items - это значения автодополнения, которые приходят из-вне и они уже отфильтрованы по введенному значению. Тут достаточно просто подсветки в существующих, без фильтрации.

2020-09-22 12:06 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +            <Paragraph hasMargin={false}>
А тут действительно нужен параграф? Нужны его стили?

2020-09-22 12:06 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +                            ? <span className={cn('highlighted-fragment')}>{fragment}</span>
Видимо не хватает теста на подстветку.

2020-09-23 13:17 UTC, jekatigr requested changes

2020-09-23 13:17 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +    /** Selected value. Should correlate with items.value */
Видимо нужно подправить описание. В items уже нет объектов и корреляция не обязательна.

2020-09-23 13:17 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +    /** Debounce delay */
Может,
```suggestion
    /** Debounce delay for onChange callback */
```

2020-09-23 13:17 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.less
> +        width: 5%;
Иконка все еще уменьшается при ресайзе и все еще присутствует отступ справа от нее.

2020-09-23 13:17 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.mdx
> +                onChange={onSubmit}
Можно сюда добавить:
```suggestion
                onChange={onSubmit}
                changeDelay={50}
```

2020-09-23 13:17 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.mdx
> +export const DemoSearchWrapper: React.FC<IDemoSearchWrapperProps> = ({ children }) => {
Нужно обновить листинг.

2020-09-23 13:17 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +            <div>
Тут даже div не нужен вроде как
```suggestion
            <>
```

2020-09-23 13:17 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.test.tsx
> +            expect(mockedDebounce).toBeCalledWith(expect.any(Function), 250);
Не гарантирует, что onChange не вызывался перед истечением таймаута. Лучше через mockTimers "подвигать" время, чтобы убедиться, что до changeDelay onChange не вызывался, но вызвался после.
И лучше передать changeDelay явно с другим значением, не по умолчанию.

2020-09-23 13:17 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.test.tsx
> +            expect(props.onChange).toBeCalledWith('new value');
Если проверять вызовы мокнутой функции в глобальной переменной props, то тесты будут зависеть друг от друга, т.к. мок функции уже использовался и "загрязнен". Правильно прямо в тесткейсе создать новый jest.fn, передать в пропсах его и его же и проверять. К другим тесткейсам тоже относится.

2020-09-23 17:34 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Search/Search.tsx
> +    /** Debounce delay */
может

2020-09-23 17:45 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Search/Search.less
> +        width: 5%;
отступ был поправлен, макета для этого компонента нет, поэтому я на мобилке прировняла правый отступ к левому - 24px.

2020-09-24 13:04 UTC, jekatigr requested changes

2020-09-24 13:04 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.less
> +            padding: 0 55px 0 25px;
В TextField точно есть такие параметры? Возможно это лишнее.

2020-09-24 13:04 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +    /** Current selected value */
```suggestion
    /** Current value */
```
Выбирать не из чего, это не комбобокс.

2020-09-24 13:04 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.test.tsx
> +            jest.advanceTimersByTime(300);
Сейчас тест не проверяет, что handleChange не был вызван до задержки.
```suggestion
            jest.advanceTimersByTime(250);
            expect(handleChange).notHaveBeenCalled(1);
            jest.advanceTimersByTime(300);
            expect(handleChange).toHaveBeenCalledWith('new value');
```

2020-09-24 13:25 UTC, IGoRFonin commented on packages/ui-core/src/components/Search/Search.tsx
> +const cn = cnCreate('mfui-search');
`mfui-beta-search`

2020-09-25 10:56 UTC, merged