MFRU-7684 not complited fixes
MegafonWebLab/megafon-ui pull request #317
Opened 2020-08-14 10:36 UTC by fruktovoe-ragu

2020-08-18 14:16 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +    getCurrentIndex = () => {
Если я правильно понимаю, это нужно для случая, когда фокус должен проставляться на выбранный ранее элемент при переоткрытии выпадашки. Но тогда логично это делать перед открытием, а не после закрытия. Еще помню проблему с первоначально заданным значением - его скорее нужно обрабатывать отдельно от выбранного элемента, а то попытка обновления стейта проиходит фактически просто так в большинстве случаев.

2020-08-18 14:21 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +        it('it ren ders Select', () => {
```suggestion
        it('it renders with default props', () => {
```

2020-08-18 14:22 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +        it('it renders Select with props', () => {
Выше в describe уже описано, что эти тесты относятся к селекту
```suggestion
        it('it renders with props', () => {
```

2020-08-18 14:25 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            const handleClick = jest.fn();
Эм. Но ведь этот обработчик никуда не прокидывается...

2020-08-18 14:25 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +    describe('states of select', () => {
```suggestion
    describe('validation states of select', () => {
```

2020-08-18 14:26 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            const wrapper = shallow(<Select items={[]} verification={Verification.VALID} />);
Текст тоже стоит добавить, у него же добавляется кастомный класс. Ниже тоже.

2020-08-18 14:29 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            expect(mockedDebounce).toBeCalledWith(expect.any(Function), 250);
Внутренняя реализация. В тесте должно быть не важно, что эта функция вызвана. Если нужно протестить, что onChange вызывается не сразу - можно через jest.mockTimers "подвигать время" и проверять был ли вызван колбэк.

2020-08-18 14:30 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +    describe('typing', () => {
Может так?
```suggestion
    describe('key typing handlers', () => {
```

2020-08-18 14:31 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            wrapper.find(`.${cn('combobox')}`).simulate('change', {
Кстати, а с initial value заработает подсветка?

2020-08-18 14:47 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            expect(wrapper.state('isOpened')).toBeFalsy();
Вроверка стейта = проверка внутренней реализации. Нужно проверять верстку, а не стейт.

2020-08-18 14:49 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            expect(wrapper.state('inputValue')).toEqual(props.items[0].title);
Незнакомая нотация, но вроде тоже проверка стейта, нужно смотреть верстку.

2020-08-18 14:49 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            const listItemActive = 'mfui-select__list-item_active';
Это видимо тоже лучше через cn оформить.

2020-08-18 14:50 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            const listItemActive = 'mfui-select__list-item_active';
cn

2020-08-18 14:51 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            expect(handleSelectItem).toHaveBeenCalled();
Тут еще можно проверять объект, с которым колбэк был вызван.

2020-08-18 14:54 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +    getCurrentIndex = () => {
Плюс из-за этой замены сломалась фильтрация. Кейс: выбрать значение, отфильтровать так, чтобы выбранного в списке не было. Переоткрыть список, попробовать что-то выбрать.

2020-08-18 14:55 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.mdx
>  <Playground>
Кажется меню слева сломалось в доке.

2020-08-18 14:56 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
>          }
Проверки на instanceof видимо нужно выпилить, это мешает в тестах на проекте. Надо подумать, чем ее заменить и надо ли.

2020-08-20 17:21 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            wrapper.find(`.${cn('combobox')}`).simulate('change', {
не понимаю. Какой initial value?

2020-08-20 21:55 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            wrapper.find(`.${cn('combobox')}`).simulate('change', {
Ну значение в текстовое поле можно передать из-вне компонента, я про это значение.

2020-08-24 12:22 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Select/Select.mdx
>  <Playground>
не сломано, просто перенос есть. Как, например, в компоненте Button у пропса passiveColor

2020-08-24 13:17 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Select/Select.mdx
>  <Playground>
Убрать типизацию для аргументов не могу, ошибка вылазит. А повлиять на стили интерфейса нет возможности

2020-08-25 15:14 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            expect(handleSelectItem).toHaveBeenCalled();
Есть подозрение, что в самом тесте нет смысла. Вероятно при открытии выпадающего меню и при нажатии на Enter, браузер как-то сам фокусируется на первом элементе и выбирает его. В тестах такое поведение отловить никак не получается.
Сам выбор элемента, который происходит с помощью функции handleSelectItem, уже описан в другом тесте. А вот этот вариант с Enter не получается отследить тестами

2020-08-26 08:34 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            expect(wrapper.state('inputValue')).toEqual(props.items[0].title);
ниже написала, почему я удалила этот тест

2020-08-28 13:34 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            expect(mockedDebounce).toBeCalledWith(expect.any(Function), 250);
onChange вызывается каждый раз. Не понятно, что тестировать

2020-09-25 14:08 UTC, jekatigr requested changes

2020-09-28 13:39 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Select/Select.tsx
> +        if (this.selectNode.contains(e.target as Node) || !isOpened) {
хм, без этих наворотов работает отлично) Так что даже аргумент e становится ненужным

2020-09-29 10:34 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +        it.only('calls onChange while typing in the field with debounce', async () => {
```suggestion
        it('calls onChange while typing in the field with debounce', async () => {
```

2020-09-29 10:42 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +        if (!isOpened) {
Условие проверяло, что по клику на сам селект - выпадашка не закроется. Сейчас не правильно.

2020-09-29 10:43 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> -        this.setState((state) => ({ isOpened: !state.isOpened }));
Это нужно вернуть.

2020-09-29 10:46 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.test.tsx
> +            const wrapper = shallow(<Select {...props} type={SelectTypes.COMBOBOX} />);
Лучше передать отличное от дефолта значение.

2020-09-29 11:22 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Select/Select.tsx
> +        if (this.selectNode.contains(e.target as Node) || !isOpened) {
как же я ошибалась

2020-10-02 19:08 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
>      renderTitle() {
Баг, воспроизводится в доке на селекте с иконками станций:
1. открыть селект, выбрать значение
2. нажать Tab, чтобы фокус сместился на следующий выключенный селект
3. нажать Enter - выпадашка откроется, хотя не должна.

2020-10-02 19:14 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
>      renderTitle() {
Не помню, обсуждалось ли это, но в комбобоксе при клике на поле ввода выпадашка не открывается сразу, хотя это было бы удобнее. В кейсе с фильтрацией на сколько помню в старой реализации в выпадашке показывались все элементы до момента изменения введенного текста.

2020-10-02 19:37 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
>      renderTitle() {
Комбобокс падает:
1. Выбрать значение
2. Удалить один символ и нажать Enter

2020-10-02 19:40 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
>      renderTitle() {
Проблема с выбором элемента:
1. Выбрать последнюю станцию
2. Отфильтровать по "Авиа"
3. После этого не будет возможности переключать выбранный элемент стрелками, ничего не подсвечивается.

2020-11-02 12:42 UTC, jekatigr requested changes

2020-11-02 12:42 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +            return;
return не нужен вроде как

2020-11-02 12:42 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
>      constructor(props: ISelectProps) {
Конструктор лучше перенести наверх.

2020-11-02 12:42 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.mdx
>              )}
Нужно ребейзнуться и привести доку в соответствие с новыми правилами.

2020-11-03 09:48 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +    /** Дополнительный текст */
```suggestion
    /** Дополнительный текст под полем. Свойство verification влияет на цвет текста. */
```

2020-11-03 09:50 UTC, jekatigr commented on packages/ui-core/src/components/Select/doc/Select.example.mdx
>  const DemoSelectWrapper = props => {
Заголовки ниже тоже нужно перевести.

2020-11-03 09:50 UTC, jekatigr commented on packages/ui-core/src/components/Select/doc/Select.example.mdx
>      <div style={flexStyle}>
Обертки со стилями больше не нужны, стили можно прокидывать сразу в Playground. Это улучшит читабельность примеров.

2020-11-03 09:52 UTC, jekatigr commented on packages/ui-core/src/components/Select/doc/Select.props.mdx
> +const items = [
Этот массив относится не к пропсам, а к примерам, нужно перенести его в examble.mdx

2020-11-03 16:01 UTC, merged