7872 button ui
MegafonWebLab/megafon-ui pull request #324
Opened 2020-08-18 17:14 UTC by myfka

2020-08-21 08:08 UTC, IGoRFonin commented on packages/ui-core/src/components/Button/Button.less
> +        }
лучше попробовать сделать `&&_type_primary&_disabled` чем через `!important`. Ниже по коду тоже поправь, если будет работать(должно)

2020-08-24 17:42 UTC, jekatigr requested changes

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.mdx
> +        <ButtonWrapper>
А он действительно нужен "поверх" каждой кнопки? Проверил, не нужен. Можно решить через flex у BlockWrapper. В текущем виде код примера очень загружен.

customStyles для ButtonWrapper используется только один раз и также можно заменить их на стили из обертки.

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +        (type === 'primary') && (theme === 'black') ? 'green' : theme
Не правильнее ли создать enum и сравнивать со значениями из него? Понятно, что тут два сравнения на весь компонент, но это прецедент в контексте либы. (если с enum, то его листинг нужно добавить в доку под таблицу пропсов)

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
>          return (
return не нужен

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +    const renderChildrenElem: JSX.Element = React.useMemo(() => (
```suggestion
    const renderChildren: JSX.Element = React.useMemo(() => (
```

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +    /** Custom classes for button and button text-area */
```suggestion
    /** Custom classes for button and button content */
```
Не уверен, что text-area это содержимое контейнера кнопки.

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +    children?: JSX.Element[] | Element[] | JSX.Element | Element | string;
Лишнее из-за FC.

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
>  export interface IButtonProps {
prop-types

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.test.tsx
> +            const wrapper = shallow(<Button {...props} >button</Button>);
```suggestion
            const wrapper = shallow(<Button {...props}>button</Button>);
```

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.mdx
> +            <Button sizeDesktop="large" sizeTablet="medium" sizeMobile="small" showArrow>Button</Button>
```suggestion
            <Button sizeDesktop="large" sizeTablet="medium" sizeMobile="small" showArrow>Adaptive</Button>
```

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.test.tsx
> +        it('should render with left icon', () => {
По-хорошему, я бы разделил эти два кейса: проверка рендера с иконкой и проверка, что рендер с указанными стрелкой и иконкой будет таким же, как с иконкой.

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.test.tsx
>              expect(preventDefault).toBeCalled();
```
             it('doesn't calls when disabled is true', () => {
```

И preventDefault мокать и проверять не нужно (в тесте выше тоже), это внутренняя реализация.

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.test.tsx
> +
```suggestion
```

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +        (type === 'primary') && (theme === 'black') ? 'green' : theme
Нужен отдельный тест-кейс на эту проверку.

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.test.tsx
> +            const SomeButton = require('./Button').default;
А его точно нужно rerequire'ить? Просто кажется, что это решается гораздо проще - выше мок создается не с одним значением, а с функцией равной jest.fn, а потом меняется возвращаемое значение в тесте.

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +    classes?: {
Не помню обоснование, но className тоже должен остаться.

2020-08-24 17:42 UTC, jekatigr commented on packages/ui-shared/src/components/ProductTile/ProductTileBuy.tsx
> -                        className={cn('button', { 'single-button': !showConnectButton })}
Хотя вот кейс, когда лучше было оставить.

2020-08-26 08:31 UTC, merged