8038 tile
MegafonWebLab/megafon-ui pull request #325
Opened 2020-08-19 13:33 UTC by fruktovoe-ragu

2020-08-19 17:30 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.less
> +@{d} {
Эти стили относятся только к демке. Их не должно быть в самом компоненте, т.к. они к нему не относятся и не должны с ним распространяться. Инлайново можно сделать например.

2020-08-19 17:32 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.less
> +        cursor: pointer;
Получается, что курсор-указатель только для этого типа shadow, но это не совсем верно. По идее, должна быть привязка к наличию ссылки, а не к тени.

2020-08-19 17:40 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.mdx
> +## Square Tile with different shadow type with light background
Кажется, что можно 4 playground-а объединить в два. А то страницу скроллишь, а ничего вроде бы не меняется. Может сделать два с разными скруглениями, а в каждом из них два фона? Или наоборот, темы разнести, скругления совместить.

Т.е. например такие playground-ы:
1. квадратные и круглые с темой light
2. квадратные и круглые с темой dark
3. карточки со ссылками
4. карточки с interactive, чтобы все поднимались

2020-08-19 17:41 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.mdx
> +## Square Tile with different shadow type with light background
И желательно как-то сократить заголовки) Они же отображаются в меню справа и не особо читаются. Если нужно дополнительное описание, лучше под заголовком описать дополнительно.

2020-08-19 17:42 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.mdx
> +# Tile
Может еще пример со ссылками добавить?

2020-08-19 17:52 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.mdx
> +<Props of={Tile} />
Нужны листинги перечислений.

2020-08-26 12:54 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Tile/Tile.tsx
> +    onClick: PropTypes.func,
а здесь не получится добавить children, иначе ts будет жаловаться, что и в ITileProps тоже ожидается children

2020-08-28 00:38 UTC, jekatigr requested changes

2020-08-28 00:38 UTC, jekatigr commented on packages/ui-shared/CHANGELOG.md
>  # [2.0.0-beta.0](https://github.com/MegafonWebLab/megafon-ui/compare/@megafon/ui-shared@1.0.29...@megafon/ui-shared@2.0.0-beta.0) (2020-08-26)
changelog'и больше не нужно редактировать руками в мастере

2020-08-28 00:38 UTC, jekatigr commented on packages/ui-core/CHANGELOG.md
changelog'и больше не нужно редактировать руками в мастере. Из-за этого кстати конфликты.

2020-08-28 00:38 UTC, jekatigr commented on README.md
> +[![Github Actions](https://github.com/MegafonWebLab/megafon-ui/workflows/megafon-ui%20CI/badge.svg)](https://github.com/MegafonWebLab/megafon-ui/actions)
Эта правка уже есть в мастере, странно что она повторяется тут.

2020-08-28 00:38 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.tsx
> +import React from 'react';
Имя коммита на текущий момент неправильное. Тут добавлен новый компонент, т.е. тип должен быть не fix, а feat. И описание тоже явно не 'added fixes'.

2020-08-28 00:38 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.tsx
> +const cn = cnCreate('mfui-tile');
```suggestion
const cn = cnCreate('mfui-beta-tile');
```
Забыл про это упомянуть. Чтобы первая и вторая версия либы в проектах не конфликтовали из-за измененых стилей. А после релиза второй версии можно было во всем проекте заменить.

2020-08-28 00:38 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.mdx
> +```javascript
В остальных компонентах сначала идет таблица пропсов, а потом листинги. Лучше сделать консистентно.

2020-08-28 00:38 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.mdx
> +## Tiles with links and shadow on hover
Можно просто 
```suggestion
## Interactive tiles
```
1. В этом примере лучше не использовать ссылки, они были в предыдущем. Смысл этого - показать изменение при наведении мыши, но не более.
2. theme=dark предназначена для тени на темном фоне, тут фон светлый. Да и не нужно делать его темным, пример не об этом. Лучше просто убрать theme="dark".

2020-08-28 00:38 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.mdx
> +        <div style={tileView}>
Код примеров очень "перегружен", сложно воспринимать что относится к компоненту, а что к примеру. Может можно убрать обертки над каждой плиткой, а оставить только для строк? Через flexbox или как в примере у Button с гридами.

2020-08-28 00:38 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.test.tsx
> +        it('calls mouseEnter', () => {
Тест не про вызов mouseEnter, кейс не в этом. Тут тестируется реакция на наведение мыши. 
```suggestion
        it('should render shadow on mouse enter', () => {
```

Ниже тоже самое.

2020-08-28 00:38 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.test.tsx
> +            expect(wrapper).toMatchSnapshot();
Достаточно либо этой строки, либо следующей. Они обе по сути проверяют одно и то же. В тесте ниже тоже.

2020-09-14 16:10 UTC, jekatigr requested changes

2020-09-14 16:10 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.docz.tsx
> +export const darkFlexStyle = {
```suggestion
export const darkFlexStyle = {
    ...lightFlexStyle,
    backgroundColor: '#00B956',    
}
```

2020-09-14 16:10 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.docz.tsx
> +export const lightFlexStyle = {
Непонятно зачем эти стили экспорируются, в mdx они не используются.

2020-09-14 16:10 UTC, jekatigr commented on packages/ui-core/src/components/Tile/Tile.docz.tsx
> +        wrapperTheme: string;
```suggestion
        wrapperTheme: 'light' | 'dark';
```

2020-09-14 16:32 UTC, merged