feat(benefits with a picture): added new component
MegafonWebLab/megafon-ui pull request #339
Opened 2020-08-31 16:23 UTC by VinokurovAlexander

2020-08-31 17:02 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +    switch (count) {
Лучше разбить это на две функции типа getCenterLargeConfig и getCenterMediumConfig, и в отдельной функции с помощью swith определять какую из трех вызывать. Иначе слишком громоздкая функция получается

2020-08-31 17:03 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +                    // wide
Мне кажется это лишyее, по названию поля и так понятно wide это или desktop

2020-08-31 17:09 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +const DESKTOP_MIDDLE_START = 1280;
Это нужно в файл src/constants/breakpoints.ts поместить, контрольные точки должны быть едиными для компонентов и лежать в одном месте, что бы потом при их смене не лазить по всему проекту

2020-08-31 17:12 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.docz.tsx
> +// @ts-ignore
Нужно в файле custom-typings.d.ts объявить тип для png

declare module '*.png' {
    const content: any;
    export default content;
}

2020-08-31 17:16 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.mdx
> +
Лишние линии

2020-08-31 17:17 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +export interface IBenefitsPictures {
Перенеси после или перед объявлением констант, не нужно мешать все это

2020-08-31 17:21 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitPictures.test.tsx
> +                expect(wrapper).toMatchSnapshot();
Лишний отступ

2020-08-31 17:42 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +    if (gutterSize === 'medium') {
Подобные строки нужно помещать в константы, а данном случае лучше enum, с его помощью можно и типа сразу указать и в коде использовать. Со строкой, которая множество раз используется в коде легко опечататься и не заметить ошибку, enum не даст сделать опечатку в названии переменной.

2020-08-31 17:42 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +    const isLargeGutter = gridGap === 'large';
enum

2020-08-31 17:43 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +                hAlign={hAlign === 'center' && items.length !== 3 ? 'center' : 'left'}
enum

2020-08-31 17:43 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +                        {...hAlign === 'left'
enum

2020-08-31 17:44 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +    hAlignImg?: 'left' | 'center';
И в типах пропсов соответственно enum

2020-08-31 17:45 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +            setCurrentGutter('medium');
enum

2020-08-31 17:50 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.mdx
> +        items={twoItemsWithShortImg}
Нужна секция Included props в самом низу, в которой показывается какая структура данных у этих переменных, иначе стороннему пользователю библиотеки остается только догадываться, что скрывается за Ibenefit[] Посмотри BenefitsIcons.mdx

2020-08-31 17:53 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +
Мы обычно не делаем отбивку в начале функции

2020-09-08 16:48 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitPictures.test.tsx
> +    hAlignImg: HorizontalAlign.LEFT,
Этот пропс не нужен, выравнивание картинки должно зависеть от выравнивания колонки, других вариантов не должно быть

2020-09-08 16:48 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +    hAlignImg?: HorizontalAlign;
Этот пропс не нужен, выравнивание картинки должно зависеть от выравнивания колонки, других вариантов не должно быть

2020-09-08 16:50 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +    hAlign?: 'left' | 'center';
Это тоже enum

2020-09-08 17:00 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +                    hAlign === HorizontalAlign.CENTER && items.length !== 3
Это лучше в константу положить, тернарник станет короче и в одну строку

2020-09-08 17:01 UTC, n-ilyin commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +                            })}
Что то с выравниванием параметров не то

2020-09-14 14:04 UTC, Gashaal requested changes

2020-09-14 14:04 UTC, Gashaal commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +    const isGridCenterAlign = hAlign === HorizontalAlign.CENTER && items.length !== 3;
не совсем понятно, почему 3, может создать константу c подходящим именем? например, `const ONLY_LEFT_ALIGN_COUNT = 3;`

2020-09-14 14:13 UTC, jekatigr commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.docz.tsx
> +const img = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAcgAAAECCAIAAAD1sNBvAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA7E
Главное, чтобы эти картинки из папки demo не появились в пакете при сборке.

2020-09-15 11:37 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/BenefitsPictures/types.ts
> +type TGridSizeValues = '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '12';
Решили пока оставить так. А в дальнейшем использовать импорты.

2020-09-15 11:38 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +    const resizeHandler = () => {
Запретить пользователю ресайзить окно мы точно не можем, а там есть отличия компонента в мобильной и десктопной версии, поэтому думаю стоит учесть такой момент.

2020-09-15 11:44 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +const getLeftConfig = (count: number, index: number): GridConfig => {
Манипуляции с конфигом нужны для соответствия макетам.  Там много кейсов с разными отступами, количеством элементом в контейнере + адаптив.  Макеты можно здесь посмотреть: https://www.figma.com/file/pdlMZ3xqKFBc8IWyCLqfd3/%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80_%D0%92%D1%91%D1%80%D1%81%D1%82%D0%BA%D0%B0?node-id=1%3A2040

2020-09-15 11:45 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/BenefitsPictures/types.ts
> +export type GridConfig = {
Решили пока оставить так

2020-09-15 11:57 UTC, VinokurovAlexander commented on packages/ui-core/src/constants/breakpoints.ts
> +export const DESKTOP_MIDDLE_START = 1280;
Да, договорились создать единый файл на проекте с брейкпоинтами. Можно его перенести в shared, только если 
 понадобится его использовать в core как тогда поступать?  Дублировать? 
@jekatigr @n-ilyin

2020-09-15 12:10 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.docz.tsx
> +const img = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAcgAAAECCAIAAAD1sNBvAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA7E
Вроде ок, не появляются

2020-09-15 12:14 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.mdx
> +const twoItems = [
Эта переменная нужна как пример структуры пропса items. Т.к. выше в разделе пропсов компонента запись Ibenefit[] нам ни о чем не говорит

https://i.imgur.com/rjBTqS4.png

2020-09-18 09:04 UTC, Gashaal commented on packages/ui-core/src/constants/breakpoints.ts
> +export const DESKTOP_MIDDLE_START = 1280;
В каком-то реквесты видел файл с брейкпоинтами...
Наверное, стоит оставить в ui-core, раз мы оттуда импортируем cnCreate и пр

2020-09-18 10:39 UTC, jekatigr commented on packages/ui-core/src/constants/breakpoints.ts
> +export const DESKTOP_MIDDLE_START = 1280;
Вообще тема с изменениями компонентов из под js при ресайзе - это вряд ли про гайдовые компоненты из ui-core, т.е. очень вряд ли что там эти константы вообще понадобятся. Можно оставить их в shared и если что позже перетащить.

2020-09-20 14:50 UTC, Gashaal approved these changes

2020-09-21 17:09 UTC, jekatigr commented on packages/ui-core/package.json
> +    "lodash.throttle": "^4.1.1",
Почему зависимость добавилась в core, хотя все изменения в shared?

2020-09-21 17:11 UTC, jekatigr commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +const cn = cnCreate('benefits-pictures');
Имя класса должно быть с префиксом либы.

2020-09-22 10:33 UTC, jekatigr requested changes

2020-09-22 10:33 UTC, jekatigr commented on packages/ui-shared/src/components/BenefitsIcons/BenefitsIcons.tsx
> +const cn = cnCreate('mfui-benefits-icons');
Пока что добавляем префикс с beta, чтобы потом все разом заменить.

2020-09-22 10:33 UTC, jekatigr commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.mdx
> +<Props of={BenefitsPictures} />
Нужен листинг IBenefit под таблицей, иначе непонятно что туда передавать.

2020-09-22 10:33 UTC, jekatigr commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +const cn = cnCreate('mfui-benefits-pictures');
```suggestion
const cn = cnCreate('mfui-beta-benefits-pictures');
```

2020-09-22 10:33 UTC, jekatigr commented on packages/ui-shared/src/components/BenefitsIcons/BenefitsIconsTile.tsx
> +const cn = cnCreate('mfui-benefits-icons-tile');
```suggestion
const cn = cnCreate('mfui-beta-benefits-icons-tile');
```

2020-10-02 17:47 UTC, merged