feat(video block): add a new component
MegafonWebLab/megafon-ui pull request #342
Opened 2020-09-02 09:33 UTC by VinokurovAlexander

2020-09-08 17:38 UTC, n-ilyin commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.test.tsx
> +    });
mediaSource не передан ни в одном из тестов

2020-09-18 09:51 UTC, Gashaal requested changes

2020-09-18 09:51 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +    mediaType?: 'video' | 'youtube' | 'gif';
Может стоит вынести в enum?

2020-09-18 09:51 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.test.tsx
> +describe('<VideoBlock />', () => {
стоит добавить тест для `mediaType="video"`

2020-09-18 09:51 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.mdx
> +## Video content
Стоит добавить кейсы с video и youtube

2020-09-18 10:45 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +interface IContentData {
```suggestion
interface IContent {
```

2020-10-07 09:15 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +                    <img className={cn('image')} src={mediaSource} alt="gif"/>
Обсудили с Антоном это вопрос. Решили отказаться от гифок.

2020-10-07 09:29 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +                        <source className={cn('source')} src={mediaSource} type="video/mp4" />
В статье показан пример конвертации gif в webm, а mp4 в webm у меня не удалось сконвертировать с уменьшением размера файла. Пока зальём так, видимо, если понадобится использовать другие форматы - доработаем.

2020-10-07 09:30 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +    mediaType?: 'video' | 'youtube' | 'gif';
сейчас enum не работает при подключении либы в другой проект

2020-10-07 09:32 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.test.tsx
> +describe('<VideoBlock />', () => {
так в компоненте же по умолчанию включен данный mediaType ?

2020-10-11 15:17 UTC, Gashaal requested changes

2020-10-11 15:17 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +                <div className={cn('video-wrapper')}>
Зачем этот div? Ощущение, что можно убрать или этот div или video-banner

2020-10-11 15:17 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.less
> +        position: absolute;
Зачем position: absolute? Может можно без него?

2020-10-11 15:17 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.test.tsx
> +        const component = shallow(<VideoBlock mediaSource="mediaSource">Test paragraph text</VideoBlock>);
Для чего 'Test paragraph text'?

2020-10-11 15:17 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +                <div className={cn('inner')}>
нет стилей для этого класса

2020-10-11 19:15 UTC, Gashaal approved these changes

2020-10-11 19:15 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.mdx
> +interface IContentData {
Можно ли сделать реэкспорт из VideoBlock.tsx?

2020-10-11 19:15 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.docz.tsx
> +const content = {
стоит добавить типизацию

2020-10-11 19:15 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.mdx
> +const content = {
стоит добавить типизацию

2020-10-11 19:17 UTC, Gashaal requested changes
Request changes

2020-10-13 10:26 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +const cn = cnCreate('mfui-video-block');
```suggestion
const cn = cnCreate('mfui-beta-video-block');
```

2020-10-15 07:27 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.mdx
> +interface IContentData {
https://github.com/MegafonWebLab/megafon-ui/pull/346#discussion_r502954054

2020-10-16 14:38 UTC, Gashaal approved these changes

2020-10-16 14:53 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.mdx
> +    onButtonClick: () => alert('button click'),
Лучше без alert'ов в примерах. Это не красиво и нужно их закрывать после появления. Лучше сделать обертку с состоянием и отобразить реакцию на клик.

2020-10-16 15:44 UTC, jekatigr requested changes

2020-10-16 15:44 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +    }, [renderContent, renderVideo]);
```suggestion
    }, [content, renderContent, renderVideo]);
```

2020-10-16 15:44 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +    const renderContent = React.useMemo(() => {
Тут все переменные названы с префиксом "render", при этом ни одна из них не является функцией, а в итоге просто хранит верстку. Лучше обернуть эти функции в useCallback вместо useMemo, чтобы они вызывались в местах использования, а не сразу и всегда.

2020-10-16 15:44 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +        if (!content) {
Тогда например эта проверка не понадобится, потому что в рендере renderGridColumns уже есть проверка на существование контента и эта функция просто не вызовется, если контент не пришел.

2020-10-16 15:44 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +    }, [content]);
Если изменится что-то внутри content, а ссылка на него не поменяется - компонент не обновит отображение. Нужно это поправить, не думаю, что правильно полагаться на иммутабельность пропса.

2020-10-16 15:46 UTC, jekatigr commented on packages/ui-core/src/styles/base.less
> +@desktopBU:       ~'screen and (min-width: @{desktopBigStart})';                                        // 1440 - ∞
Не знаю, есть ли у нас "гайдовые" расширения, но тут нужно проконсультироваться с Колей.

2020-10-16 16:09 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.mdx
> +---
packages/ui-shared/demo/video.mp4 - нужно переместить в ui-shared/components/VideoBlock/docs

И 1.5мб - точно нельзя еще ужать? Качество там снизить, разрешение. Раза в три)

2020-10-16 16:15 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.mdx
> +    title: string;
Нужны описания полей, тут и в компоненте.

2020-10-16 18:09 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.less
> +        & ~ & {
Лучше обернуть параграфы в блок и стилизовать их через not(:first-child). Чтобы "изолировать и не зависеть от порядка левых дом узлов" (с) Коля.

2020-10-23 12:01 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +        if (!content) {
renderContent ничего не знает о проверке в renderGridColumns и ts все равно ругается. Сделаю content тогда как параметр функции

2020-10-26 16:15 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.mdx
> +const videoSrc = 'video.mp4' | '2Sps5MnvlKM';
Добавил в описание пропса

2020-10-30 10:13 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/doc/VideoBlock.example.mdx
> +interface IContent {
Описание этого интерфейса должно быть под таблицей пропсов в соседнем табе.

2020-10-30 10:16 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.tsx
> +    /** Источник видео. Если видео с youtube, то необходимо указать id, например 2Sps5MnvlKM */
```suggestion
    /** Источник видео. Если видео с youtube, то необходимо указать id. */
```

2020-10-30 10:17 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/doc/VideoBlock.docz.tsx
> +const youtubeVideoId = '2Sps5MnvlKM';
Нужно добавить в листинг в примере.

2020-10-30 10:19 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBlock/VideoBlock.mdx
> +---
Переместить еще нужно в директорию doc в папке компонента.

2020-11-02 10:12 UTC, merged