8175 add videobanner
MegafonWebLab/megafon-ui pull request #346
Opened 2020-09-11 09:50 UTC by VinokurovAlexander

2020-10-11 19:14 UTC, Gashaal requested changes

2020-10-11 19:14 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.mdx
> +interface IContent {
возможно сделать реэкспорт из VideoBanner.tsx?

2020-10-11 19:14 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.mdx
> +const content = {
стоит добавить тип к content

2020-10-11 19:14 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.docz.tsx
> +const image = {
тут и ниже стоит добавить типизацию

2020-10-13 11:31 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.less
> +            height: 400px;
@mobile это только до 1023, а @desktopS это начиная с 1024. Но тут все равно есть что поправить.

2020-10-13 11:37 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +                    style={{backgroundImage: `url(${isMobile ? image.mobile : image.main})`}}>
Сейчас оба значения main и mobile обязательны, на тот случай если видео вдруг не загрузится и тогда будет показываться заглушка в виде картинки.

2020-10-13 11:41 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.docz.tsx
> +import mainImage from '../../../demo/bg_grey_desktop.png';
packages/ui-shared/demo/video.mp4 - видео для демки на 24 мегабайта - это перебор. Нужно обрезать/сжать до 0.5-1 мб.

2020-10-13 11:42 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +interface IVideoBanner {
```suggestion
interface IVideoBannerProps {
```

2020-10-13 11:44 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +    }, [isMobile]);
```suggestion
    }, [isMobile, setIsMobile]);
```

2020-10-13 11:44 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +    videoType: PropTypes.oneOf(['video', 'youtube']),
Контента не хватает.

2020-10-13 12:24 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.mdx
> +interface IContent {
Здесь интерфейс нужен для отображения его структуры на странице компонента

2020-10-13 12:25 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.mdx
> +interface IContent {
Удобно было бы делать такое через экспорт, но что-то пока не вижу способов

2020-10-16 15:14 UTC, Gashaal requested changes

2020-10-16 15:14 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +    }, [isMobile, setIsMobile]);
Тут нужно указать пустой массив - нам нужно повесить ф-и `resizeHandler` на событие `resize`, `resizeHandler` без зависимостей. - https://ru.reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects

2020-11-03 13:34 UTC, Gashaal approved these changes

2020-11-03 13:42 UTC, merged