fix(select): edit item value prop type
MegafonWebLab/megafon-ui pull request #347
Opened 2020-09-14 11:00 UTC by VinokurovAlexander

MFRU-8143

2020-09-14 14:49 UTC, Gashaal requested changes
В `handleClickItem` можно использовать тип `SelectItemValueType`

2020-09-14 16:17 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +        currentValue:  PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
```suggestion
        currentValue: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
```

2020-09-16 16:42 UTC, Gashaal approved these changes

2020-09-17 10:54 UTC, Gashaal approved these changes

2020-09-17 11:22 UTC, merged