feat(checkbox): add data attrs prop
MegafonWebLab/megafon-ui pull request #349
Opened 2020-09-16 09:02 UTC by VinokurovAlexander

2020-09-16 16:50 UTC, Gashaal requested changes

2020-09-16 16:50 UTC, Gashaal commented on packages/ui-core/src/components/Checkbox/Checkbox.tsx
> +import filterDataAttrs, { IDataAttributes } from '../../utils/dataAttrs';
```suggestion
import filterDataAttrs, { IDataAttributes } from 'utils/dataAttrs';
```

2020-09-17 10:31 UTC, VinokurovAlexander commented on packages/ui-core/src/components/Checkbox/Checkbox.tsx
> +import filterDataAttrs, { IDataAttributes } from '../../utils/dataAttrs';
В итогом билде абсолютный путь работать не будет, поэтому пока пишем так. Есть задача по данному вопросу [MFRU-8111](url
![image](https://user-images.githubusercontent.com/46749400/93459224-12d1da80-f8ea-11ea-8dbb-97dae3f0c881.png)
)

https://i.imgur.com/HH1Ukos.png

2020-09-17 10:53 UTC, Gashaal approved these changes

2020-09-17 11:22 UTC, merged