feat(tooltip): new Tooltip component with ref trigger element
MegafonWebLab/megafon-ui pull request #364
Opened 2020-10-12 09:48 UTC by tasty-tasty

Как альтернатива https://github.com/MegafonWebLab/megafon-ui/pull/363.
Такой вариант реализации возник из-за validateDOMNesting warning'а в базовом варианте.

2020-10-12 12:06 UTC, jekatigr commented on packages/ui-core/package.json
>    "dependencies": {
Нужно добавить в BubbleHint warning, что компонент deprecated и будет удален в ближайших релизай беты. И что нужно переезжать на Tooltip.

2020-10-12 12:46 UTC, jekatigr requested changes

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +const IS_TOUCH_DEVICE = detectTouch();
На сервере detectTouch вернет false, на клиенте этот код уже не отработает. Нужно перенести в компонент, посмотри примеры в других компонентах.

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +type IsOpenType = boolean;
Не надо так) Лучше написать boolean в месте использования.

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    /** Open handler */
```suggestion
    /** Open callback */
```

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    /** Close handler */
```suggestion
    /** Close callback */
```

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    children?: React.ReactNode;
Лишнее, react.FC сам добавит.

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    const [isOpen, setIsOpen] = useState<IsOpenType>(isOpened);
react должен вывести тип из isOpened.
```suggestion
    const [isOpen, setIsOpen] = useState(isOpened);
```

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    const options = {
Можно обернуть в useMemo с зависимостями arrowElement и placement.

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    useEffect(() => setIsOpen(isOpened), [isOpened]);
```suggestion
    useEffect(() => setIsOpen(isOpened), [setIsOpen, isOpened]);
```
Это же тоже зависимость.

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    }, [isOpen, onClose]);
```suggestion
    }, [isOpen, onClose, setIsOpen]);
```

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    }, [isOpen, onOpen]);
```suggestion
    }, [isOpen, onOpen, setIsOpen]);
```

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +        return;
Зачем?

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +        return;
И тут.

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +                {children}
Видимо нужно затащить Tile?

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    const triggerEvents = (open, close) => {
Универсально конечно, но чрезмерно усложнено. Вряд ли эта функция будет вызвана еще хотя бы раз. А читается сложно. Лучше так (ниже есть несколько недоработок):
```suggestion
    const event: TriggerType = useMemo(() => IS_TOUCH_DEVICE ? 'click' : trigger, [trigger, IS_TOUCH_DEVICE]);

    useEffect(() => {
        if (event === Trigger.CLICK) {
            triggerElement && triggerElement.addEventListener('click', handleOpenEvent);
            if (isOpen) {
                document.addEventListener('click', handleClickOutsideEvent);
            }
            return () => {
                triggerElement && triggerElement.removeEventListener('click', handleOpenEvent);
                document.removeEventListener('click', handleClickOutsideEvent);
            };
        }
    }, [event]);

    useEffect(() => {
        if (event === Trigger.HOVER) {
            triggerElement && triggerElement.addEventListener('mouseenter', handleOpenEvent);
            if (isOpen) {
                document.addEventListener('mouseover', debounce(handleMouseOverOutsideEvent, 30));
            }
            return () => {
                triggerElement && triggerElement.removeEventListener('mouseenter', handleOpenEvent);
                document.removeEventListener('mouseover', debounce(handleMouseOverOutsideEvent, 30));
            };
        }
    }, [event]);
```

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +                    handler: debounce(handleMouseOverOutsideEvent, 30),
При удалении listener'а в removeEventListener должна передаваться ссылка на обработчик. В данном случае, debounce каждый свой вызов будет создавать новую функцию и обработчик не удалится.

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +        return () => {
Лучше снимать обработчики не при unmount'е компонента, а при закрытии тултипа. А то если со всей либы собрать такие обработчики, в глобальном документе их будет очень много.

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    triggerElement: PropTypes.any,
вряд ли тут any

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +            className={cn([className], { size: size , open: isOpen })}
```suggestion
            className={cn([className], { size , open: isOpen })}
```

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +            e.target instanceof Node &&
Условные выражения на три строки лучше разбить на несколько переменных.
```suggestion
            const isElement = e.target instanceof Element;
            const isOnPopperElement = popperElement && popperElement.contains(e.target);
            const isOnTriggerElement = triggerElement && triggerElement.contains(e.target);
            if (isElement && !isOnPopperElement && !isOnTriggerElement)
```
С логикой мог ошибиться, но примерно так. В предыдущем обработчике тоже можно две переменные создать.

2020-10-12 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +        onOpen && onOpen(e);
```suggestion
        onClose && onClose(e);
```

2020-10-12 12:50 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.less
> +.arrowSize() {
Миксины можно инлайново добавить. Дублирование будет только для shadow, но читаемость лучше.

2020-10-12 12:53 UTC, jekatigr commented on packages/ui-core/package.json
>    "dependencies": {
В тексте сообщения коммита также нужно будет пометить, что компонент задепрекейчен.

2020-10-21 14:16 UTC, jekatigr commented on packages/ui-core/package.json
>      "react-popper": "0.10.4",
Не забыть удалить при удалении bubblehint

2020-10-21 14:21 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    const event: TriggerType = useMemo(() => detectTouch() ? 'click' : trigger, [detectTouch, trigger]);
Обсуждали же. useMemo выполнится на сервере, а detectTouch там вызывать бесполезно. Нужно переместить в useEffect и в стейт.

2020-10-21 14:37 UTC, tasty-tasty commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    const event: TriggerType = useMemo(() => detectTouch() ? 'click' : trigger, [detectTouch, trigger]);
Да, потерял где-то в процессе.

2020-10-21 20:58 UTC, jekatigr requested changes

2020-10-21 20:59 UTC, jekatigr commented on packages/ui-core/package.json
>      "@babel/plugin-transform-runtime": "^7.8.3",
+ rerender on events
+ mixed controlled state

2020-10-22 17:25 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +                className={cn('arrow-container', { shadow: true })}
В смысле для тени и для стрелки. Тут два раза (теперь) используется arrow-container (ренее был arrow), один с модификатором. Хотя это разные элементы, лучше сделать arrow и arrow-shadow

2020-10-23 10:57 UTC, jekatigr requested changes

2020-10-23 10:57 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    trigger?: TriggerType;
```suggestion
    triggerEvent?: TriggerType;
```

2020-10-23 10:59 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.docz.tsx
> +export const DemoBlockWrapper = (
Листинги демо-компонентов нужно в доку добавить. Пример в Counter есть.

2020-10-23 11:02 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.mdx
> +#
```suggestion

```
И ниже.

2020-10-23 13:53 UTC, tasty-tasty commented on packages/ui-core/src/components/Tooltip/Tooltip.docz.tsx
> +export const DemoBlockWrapper = (
Расположил листинги wrapper'ов рядом с блоками где используются. Есть дублирование, но вроде так удобно, сразу можно посмотреть логику wrapper'а.

2020-10-23 15:12 UTC, tasty-tasty commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    useEffect(() => setIsOpen(isOpened), [isOpened]);
Из-за того что setState не меняется, я бы не добавил.))
Но для конвенции по либе, ок!

2020-10-23 15:49 UTC, tasty-tasty commented on packages/ui-core/package.json
>      "react-popper": "0.10.4",
Отдельным коммитом.

2020-10-28 14:19 UTC, tasty-tasty commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
>      triggerElement: (props, propName, componentName, location) => {
triggerElement должен быть React.RefObject<HTMLElement>
для prop types можно использовать PropTypes.shape({ current: PropTypes.node }).isRequired, но ts ругается

2020-10-29 09:31 UTC, jekatigr requested changes

2020-10-29 09:31 UTC, jekatigr commented on packages/ui-shared/src/components/ProductCard/ProductCardInfo.less
> +        &_tooltip {
Селекторы не ломай.

2020-10-29 09:31 UTC, jekatigr commented on packages/ui-shared/src/components/ProductCard/ProductCardInfo.tsx
> +        return children(triggerRef);
Не понимаю. Зачем тут нужен такой подход? Реф нигде не сохраняется в итоге, тоже самое можно делать внутри метода renderTooltip без render-props паттерна, который все усложняет. В остальных местах тоже.

2020-10-29 09:38 UTC, tasty-tasty commented on packages/ui-shared/src/components/ProductCard/ProductCardInfo.less
> +        &_tooltip {
ок

2020-11-02 10:50 UTC, jekatigr requested changes

2020-11-02 10:50 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/doc/Tooltip.example.mdx
> +                    Tooltip will fill the entire width of browser window.
При горизонтальном скролле увеличивается размер страницы

2020-11-02 11:18 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +        const hasPropCurrent = prop.hasOwnProperty('current');
```suggestion
        const hasPropCurrent = prop !== null && prop.hasOwnProperty('current');
```

2020-11-02 11:18 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +        if ((prop === undefined)) {
```suggestion
        if (prop === undefined) {
```

2020-11-02 14:14 UTC, tasty-tasty commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
>      triggerElement: (props, propName, componentName, location) => {
Кастомное решение ок.

2020-11-02 16:45 UTC, jekatigr requested changes

2020-11-02 16:45 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    /** Позиционирование относительно триггер элемента */
```suggestion
    /** Позиционирование относительно триггер-элемента */
```

2020-11-02 16:45 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    /** Событие на элементе триггера */
Может так?

```suggestion
    /** Тип взаимодействия с триггер-элементом для показа тултипа */
```

2020-11-02 16:45 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.tsx
> +    /** Управление внутренним состоянием снаружи */
```suggestion
    /** Управление состоянием. Компонент поддерживает контроллируемое и неконтроллируемое состояние. */
```

2020-11-02 16:45 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/doc/Tooltip.example.mdx
> +## Позиционирование относительно триггер элемента
```suggestion
## Позиционирование относительно триггер-элемента
```

2020-11-02 16:45 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/doc/Tooltip.example.mdx
> +## Устанавливаем событие триггера при первом взаимодействии с Tooltip в открытом состоянии
```suggestion
## Смена типа реакции триггера при первом взаимодействии с Tooltip в открытом состоянии
```

2020-11-02 16:45 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/doc/Tooltip.example.mdx
> +## Управление компонентом снаружи с сохранением внутренних обработчиков для элемента триггера
```suggestion
## Управление компонентом снаружи с сохранением внутренних обработчиков для триггер-элемента
```
или
```suggestion
## Управление компонентом снаружи с сохранением внутренних обработчиков для триггера
```

2020-11-02 18:59 UTC, merged