feat(banner): add new component
MegafonWebLab/megafon-ui pull request #368
Opened 2020-10-26 09:37 UTC by n-ilyin

2020-11-06 10:52 UTC, Gashaal requested changes

2020-11-06 10:52 UTC, Gashaal commented on packages/ui-core/src/components/Banner/Banner.test.tsx
> +describe('<Banner />', () => {
Стоит добавить тест для loop - проверять, что можно перейти на первый слайд с последнего и с первого на последний.
И тест для loop: false - проверить, что не можем перейти на первый слайд с последнего и тп.

2020-11-06 10:52 UTC, Gashaal commented on packages/ui-core/src/components/Banner/Banner.docz.tsx
> +export const DemoSlide = ({ children, background = '#fff' }) => {
Документацию нужно привести к виду, описанному в dev_megafon - сообщение 26.10 от Игоря Фонина.

2020-11-06 10:52 UTC, Gashaal commented on packages/ui-core/src/components/NavArrow/NavArrow.test.tsx
> +    theme: 'dark',
Стоит использовать Theme из компонента

2020-11-06 10:52 UTC, Gashaal commented on packages/ui-core/src/components/Banner/Banner.test.tsx
> +    navTheme: 'dark',
Стоит использовать NavTheme из компонента

2020-11-16 09:51 UTC, n-ilyin commented on packages/ui-core/src/components/Banner/Banner.less
> +        height: 400px;
В макете неверные значения, дизайнер так и не исправил

2020-11-16 09:51 UTC, n-ilyin commented on packages/ui-core/src/components/Banner/Banner.less
> +            height: 500px;
В макете неверные значения

2020-11-16 11:01 UTC, n-ilyin commented on packages/ui-core/src/components/Banner/Banner.tsx
> +                watchSlidesVisibility
Классы, которые добавляет этот параметр, понадобятся для реализации анимации, которую должны предоставить дизайнеры. watchSlidesProgress нам не нужен, а т.к. и без него работает, то не стал его включать, нужны только классы, без них анимацию не реализовать.

2020-11-16 11:05 UTC, n-ilyin commented on packages/ui-core/src/components/Banner/Banner.tsx
> +        swiperInstance.slideTo(loop ? index + 1 : index);
В режиме loop swiper по другому считает индексы из-за клонированных слайдов, которые ему нужны для реализация зацикленной прокрутки

2020-11-16 13:35 UTC, n-ilyin commented on packages/ui-core/src/components/Banner/Banner.test.tsx
> +describe('<Banner />', () => {
Нет возможности это протестировать, т.к. всем этим управляет swiper, который в тестах не работает из-за того, что не может вычислить размеры и координаты элементов слайдера.

2020-11-19 14:35 UTC, Gashaal approved these changes

2020-11-19 14:35 UTC, Gashaal approved these changes

2020-11-19 15:02 UTC, jekatigr commented on packages/ui-core/src/components/Banner/Banner.test.tsx
> +        expect(props.onChange).toBeCalled();
Тут очень желательно создать локальную копию с jest.fn, т.к. тут по сути "загрязняется" глобальный мок. В данных тест-кейсах как будто проблемы нет, но если бы было несколько тестов для проверки одного и того же колбэка - тесты стали бы некорректными. Можно это не заметить, либо что еще хуже - подобное решение будет копироваться в другие места, где это будет критично.

2020-11-19 15:06 UTC, jekatigr commented on packages/ui-core/src/components/Banner/BannerDot.test.tsx
> +        expect(props.onClick).toBeCalledWith(props.index);
И в этом файле.

2020-11-19 15:07 UTC, jekatigr commented on packages/ui-core/src/components/Banner/doc/Banner.example.mdx
> +export const DemoSlide = ({ children, background }) => {
Лучше в начало перенести, а то идет куча примеров с непонятным компонентом и только в конце его листинг.

2020-11-19 15:09 UTC, jekatigr commented on packages/ui-core/src/components/NavArrow/NavArrow.less
> +    -webkit-appearance: none;
autoprefixer же должен отрабатывать. Или в либе совсем старая версия?

2020-11-20 12:58 UTC, merged