feat(accordionbox): add component AccordionBox to constructor
MegafonWebLab/megafon-ui pull request #370
Opened 2020-10-28 09:10 UTC by bashmakovartur

MFRU-8324

2020-11-01 17:11 UTC, Gashaal requested changes

2020-11-01 17:11 UTC, Gashaal commented on packages/ui-shared/src/components/AccordionBox/doc/AccordionBox.mdx
> +<DoczTabs>
В документации к остальным компонентам в конструкторе и либе нет табов - описание пропсов и ниже примеры использования. Стоит привести в такому же виду. Возможно, отдельные табы имеет смысл добавлять для компонентов вроде TextField или ProductCard.

2020-11-05 11:15 UTC, n-ilyin commented on packages/ui-shared/src/components/AccordionBox/AccordionBox.less
> +    &_center-align {
У компонента Grid есть пропс hAlign и одно из значений center, которое выравнивает колонки по центру средствами flex

2020-11-05 11:31 UTC, n-ilyin commented on packages/ui-shared/src/components/AccordionBox/AccordionBox.tsx
> +    collapse?: string;
Для каких целей создавался этот класс?

2020-11-05 11:34 UTC, n-ilyin commented on packages/ui-shared/src/components/AccordionBox/AccordionBox.tsx
> +    /** Accordion title */
Вроде бы было требование писать на русском, как описания в самой демке

2020-11-09 08:21 UTC, bashmakovartur commented on packages/ui-shared/src/components/AccordionBox/AccordionBox.tsx
> +    collapse?: string;
Чтоб прокинуть класс в Collapse, Accordion использует компонент Collapse.

2020-11-10 12:29 UTC, Gashaal approved these changes

2020-11-10 12:40 UTC, merged