6972 items
MegafonWebLab/megafon-ui pull request #378
Opened 2020-10-30 14:33 UTC by n-ilyin

2020-11-10 14:32 UTC, Gashaal requested changes

2020-11-19 14:43 UTC, Gashaal approved these changes

2020-11-19 15:17 UTC, jekatigr commented on packages/ui-core/src/components/Carousel/Carousel.test.tsx
> +        expect(props.onNextClick).toBeCalled();
То же самое, что и в баннере.

2020-11-19 15:18 UTC, jekatigr commented on packages/ui-core/src/components/Carousel/doc/Carousel.example.mdx
> +export const DemoSlide = ({ children }) => {
Может тоже перенести наверх?

2020-11-19 15:20 UTC, jekatigr commented on packages/ui-core/src/components/ContentArea/doc/ContentArea.example.mdx
> +        Контент
Это из-за ребейза или умышленно?)
Длинные текстовки по идее лучше показывают использование.

2020-11-19 15:29 UTC, jekatigr commented on packages/ui-core/src/components/ContentArea/doc/ContentArea.example.mdx
> +## Отключение боковых оступов на разрешении 0 - 767
Может объединить эти три примера в один Playground? Плюс у всех примеров не видно границ области, может определить фоновый цвет для содержимого?

2020-11-19 16:58 UTC, n-ilyin commented on packages/ui-core/src/components/Carousel/Carousel.test.tsx
> +        expect(props.onNextClick).toBeCalled();
После каждого теста вызывается jest.clearAllMocks()

2020-11-19 17:02 UTC, n-ilyin commented on packages/ui-core/src/components/ContentArea/doc/ContentArea.example.mdx
> +## Отключение боковых оступов на разрешении 0 - 767
Пробовал, так сложнее понять какой пример кода к чему относится, плюс отрендеренные компоненты визуально сливаются в один и приходится городить дополнительные обертки с заголовками, что тоже затрудняет понимание.

2020-11-23 08:46 UTC, merged