Added Calendar component.
MegafonWebLab/megafon-ui pull request #382
Opened 2020-11-02 11:29 UTC by dzebisati

В рамках задачи MFRU-8217 обавил компонент Calendar.

2020-11-02 13:29 UTC, dzebisati commented
Необходимо пофиксить safari и ff и протестить в ie11
![image](https://user-images.githubusercontent.com/41205712/97873255-67110c80-1d28-11eb-8eb2-75494f0aaa8a.png)

2020-11-02 13:34 UTC, dzebisati commented
> * [ ]  Необходимо пофиксить safari и ff и протестить в ie11
Из того что накопал на эту проблему, ломается из за такой инициализации дат 
![image](https://user-images.githubusercontent.com/41205712/97873824-354c7580-1d29-11eb-8d26-8bf55b977469.png)

2020-11-03 09:27 UTC, jekatigr requested changes

2020-11-03 09:27 UTC, jekatigr commented on packages/ui-core/package.json
> +    "dayjs": "^1.9.4",
Предлагаю рассмотреть date-fns на замену dayjs.

1. она уже есть в зависимостях, т.к. ее требует datepicker-react
2. работает tree-shaking
3. вроде как больше [функциональных](https://github.com/you-dont-need/You-Dont-Need-Momentjs#feature-parity) возможностей без плагинов
4. другой подход к обработке дат. Сейчас в utils/dayjs глобально устанавливается локаль, что не правильно. Либо локально на проекте, либо в каждом методе отдельно.

2020-11-03 09:27 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/Calendar.less
> +        &_isShown {
Селекторы сломаны, тут и ниже.

2020-11-03 09:27 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/Calendar.tsx
> +    position?: 'top' | 'right' | 'bottom' | 'left';
Этого на самом деле вообще не должно быть в компоненте календаря. Это функционал тултипа. А календарь может встраиваться как в тултип, так и в любой другой компонент.

2020-11-03 09:27 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/Calendar.tsx
> +type Initials = {
Нужно перенести выше, над использующим интерфейсом.

2020-11-03 09:27 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/Calendar.tsx
> +const cn = cnCreate('mfui-calendar');
```suggestion
const cn = cnCreate('mfui-beta-calendar');
```

2020-11-03 09:27 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Day/Day.less
> +@b: e( '.mfui-calendar-day');
```suggestion
@b: e( '.mfui-beta-calendar-day');
```

2020-11-03 09:27 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Day/Day.tsx
> +const cn = cnCreate('mfui-calendar-day');
```suggestion
const cn = cnCreate('mfui-beta-calendar-day');
```

2020-11-03 09:27 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Day/Day.tsx
> +            className={cn('', modClasses)}
```suggestion
            className={cn(modClasses)}
```

2020-11-03 09:27 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Month/Month.tsx
> +const cn = cnCreate('mfui-calendar-month');
```suggestion
const cn = cnCreate('mfui-beta-calendar-month');
```

2020-11-03 09:41 UTC, dzebisati commented on packages/ui-core/package.json
> +    "dayjs": "^1.9.4",
Согласен. Изначально использовал встроенный toLocaleString, но вчера узнав об отсутствии должной поддержки в браузерах помимо хрома, в спешке заменил на dayjs.

2020-11-03 09:47 UTC, dzebisati commented on packages/ui-core/src/components/Calendar/Calendar.less
> +        &_isShown {
Не понял что именно не так 😕  Где-то в соседних компонентах подгядел, что БЭМовский модификатор уна - одно нижнее  типо `button button_red ` или ту не про это?

2020-11-03 09:50 UTC, dzebisati commented on packages/ui-core/src/components/Calendar/Calendar.tsx
> +    position?: 'top' | 'right' | 'bottom' | 'left';
Согласен, изначально на всякий пилил с функционалом тултипа, потом договорились не смешивать сущности, убрал все кроме стилизации указателя до уточнения дизайнером, указатель на всякий придержал.

2020-11-03 09:55 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/Calendar.less
> +        &_isShown {
"Сломаны" - это не "не работают", а вложены друг в друга. 
https://hq-online.megafon.ru/wiki/pages/viewpage.action?pageId=48624768

2020-11-06 12:51 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Calendar/components/Month/Month.tsx
> +                    <strong>{`${monthLabel} ${year}`}</strong>
Тег `strong` дает неправильную жирность текста, в макете она 500, как и в гайде.
ЛУчше использовать компонент Header, ну или <p> с миксином .h5()

2020-11-06 12:51 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Calendar/components/Month/Month.less
> +        font-size: 12px;
лучше бы сверстать так, чтобы можно было использовать миксин .small()

2020-11-11 14:29 UTC, closed without merging