fix(button, preloader): loader into button
MegafonWebLab/megafon-ui pull request #384
Opened 2020-11-03 14:19 UTC by fruktovoe-ragu

added preloader in button instead of spinner

2020-11-05 10:29 UTC, jekatigr requested changes

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.test.tsx
> +// import Balance from 'icons/Basic/24/Balance_24.svg';
Лишнее?

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.test.tsx
> +        // it('should render with left icon', () => {
Случайно удалено?

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +    showLoader?: boolean;
Коммит должен быть помечет breaking change, это изменение api.

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +    const isLoaderWhite = (): boolean => {
Тут не нужна функция, можно просто через boolean-переменную.

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +            case isLoaderWhite():
Это должно быть в зависимостях.

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +        root?: string | null;
а зачем тут null?

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
>      ), []);
Теперь нужно дополнить зависимости, предыдущий спиннер не зависел ни от чего.

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +            color={getLoaderColor}
```suggestion
            color={loaderColor}
```

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Button/__snapshots__/Button.test.tsx.snap
> +exports[`<Button /> layout it renders loader 1`] = `
Нужно добавить тесты для изменения лоадера при другом разрешении и для всех других вариантов рендера с цветами.

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Button/doc/Button.example.mdx
>  <Playground style={blockStyle}>
Может еще добавить пример с размерами и лоадером?

2020-11-05 10:29 UTC, jekatigr commented on packages/ui-core/src/components/Preloader/Preloader.tsx
>  import './Preloader.less';
Эти изменения лучше в отдельный коммит выделить.

2020-11-05 12:38 UTC, fruktovoe-ragu commented on packages/ui-core/src/components/Button/Button.test.tsx
> +// import Balance from 'icons/Basic/24/Balance_24.svg';
ой

2020-11-06 15:50 UTC, jekatigr requested changes

2020-11-06 15:50 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +        theme = ButtonThemes.GREEN,
Тут нужно использовать строки. В Preloader тоже. Связано с отображением таблицы пропсов в доке, если будут не строки, то непонятно какое именно будет дефолтное значение.

2020-11-06 15:50 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
>      ), [theme]);
```suggestion
    ), [type, theme]);
```

2020-11-06 15:50 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +    }, []);
```suggestion
    }, [type, theme]);
```

2020-11-06 15:50 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +        return (
return не нужен

2020-11-06 15:50 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
> +    ), [sizeAll, sizeWide, sizeDesktop, sizeTablet, sizeMobile]);
Нужно или функцию getLoaderSize вынести из компонента, либо обернуть в колбэк и добавить сюда в зависимости. Нужно для того, чтобы впоследствии при изменении кода было меньше шансов упустить зависимость.

2020-11-06 15:50 UTC, jekatigr commented on packages/ui-core/src/components/Preloader/Preloader.tsx
> +    return (
return не нужен

2020-11-06 15:50 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.less
>          margin-right: -8px;
Поправь еще пожалуйста описания в коммитах для breaking

2020-11-06 16:20 UTC, jekatigr commented on packages/ui-core/src/components/Button/Button.tsx
>      ), [contentClassName, showArrow, children]);
```suggestion
    ), [iconLeft, contentClassName, showArrow, children]);
```

2020-11-09 10:19 UTC, merged