Mfru 8217
MegafonWebLab/megafon-ui pull request #395
Opened 2020-11-10 18:51 UTC by Rakot1234

2020-11-11 15:28 UTC, jekatigr requested changes

2020-11-11 15:28 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Month/Month.tsx
> +    <div className={cn('')}>
```suggestion
    <div className={cn()}>
```

2020-11-11 15:28 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Month/Month.less
> +    &__weekday-lables {
```suggestion
    &__weekday-labels {
```

2020-11-11 15:28 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Month/Month.tsx
> +const cn = cnCreate('mfui-beta-calendar-month');
Аналогично с названием.

2020-11-11 15:28 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +<Playground>
Это не нормально, высота должна быть одинаковая. Т.е. последняя строка всегда должна присутствовать, календарь не должен прыгать.

![image](https://user-images.githubusercontent.com/2889932/98828065-aa662c00-2448-11eb-9198-fc1d21c0e0d8.png)

2020-11-11 15:28 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +            ({ handleChange, startDate, endDate }) =>
Такой ситуации не должно быть:
![image](https://user-images.githubusercontent.com/2889932/98828932-b0a8d800-2449-11eb-92c6-5265d90f5238.png)
Либо должна быть одна дата в выбранном интервале (с 01.01.2000 по 01.01.2000), либо не должно быть второй (с 01.01.2000 по undefined). Сейчас пользователь может ничего не менять и в состоянии будет неожиданный для него интервал.

2020-11-11 15:28 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +<Playground>
Этот пример лучше объединить с предыдущим. Особой разницы нет, а как они работают в связке - показать надо.

2020-11-11 15:28 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/types.ts
> +import { FirstDayOfWeek, MonthType } from '@datepicker-react/hooks';
Точно нужен отдельный файл для этого? Вроде все типы удобнее располагать в местах использования, рядом с компонентом.

2020-11-11 15:28 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/types.ts
> +export default {};
Лишнее.

2020-11-11 22:22 UTC, Rakot1234 commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +<Playground>
Данное замечание пока не правил, т.к. непонятно нужен ли функционал

2020-11-12 10:24 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +    <WithBlockedDates>
Нужны еще коды оберток. Посмотри на пример в тултипе.

2020-11-12 10:26 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +<Playground>
Высота календаря при переключении между месяцами точно не должна меняться, вне зависимости от количества отображаемых месяцев.

2020-11-12 14:19 UTC, jekatigr commented on packages/ui-core/scripts/globalSetup.ts
> +    process.env.TZ = 'UTC';
Возможно можно обойтись без глобальных переменных, если в ключах задавать дату не в виде строки, а в виде таймстампа.

2020-11-12 22:00 UTC, Rakot1234 commented on packages/ui-core/scripts/globalSetup.ts
> +    process.env.TZ = 'UTC';
Мне кажется что так проще) В том плане что указать при разработке самостоятельно таймстамп, не получив его предварительно с помощью JS, поэтому это просто очень неудобно

Глобальная переменная же, в принципе, никак не аффектит негативно на проект. Как второй вариант, можно в скрипт запуска тестов добавить таймзону, будет примерно test: 'TZ=UTC && jest'

2020-11-16 10:44 UTC, jekatigr requested changes

2020-11-16 10:44 UTC, jekatigr commented on packages/ui-core/package.json
>          }
Осталась проблема с выбранными соседними датами - 9 и 10 например. Не работает показ серого интервала.

2020-11-16 10:44 UTC, jekatigr commented on packages/ui-core/package.json
>        }
Не работает ховер над датами, при этом срабатывает на нажатие ЛКМ. Нужно поправить стили согласно макету. Дата должна "выбираться" на mouseup.

2020-11-16 10:44 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +export const SimpleCalendar = ({ children }) => <div style={wrapperStyles}>{children()}</div>;
В этом компоненте нет смысла, wrapperStyles можно напрямую положить в Playground, чтобы избавиться от оберток.

2020-11-16 10:44 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +export const SimpleCalendar = ({ children }) => <div style={wrapperStyles}>{children()}</div>;
Аналогично.

2020-11-16 10:44 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +    <div style={wrapperStyles}>
Тут стили тоже можно в Playground перенести. Чем чище код примера - тем лучше.

2020-11-16 10:44 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +        {children({ minBookingDate, maxBookingDate, unavailableDates })}
Вообще, для демонстрации здесь не нужна функция внутри children. Лучше напрямую передать inline-даты, а не передавать переменными. Иначе нужно было бы добавлять выше в листинг обертки значения этих переменных.

2020-11-16 10:44 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +                {children({ handleChange, startDate, endDate })}
И тут непонятно, зачем функция, чтобы стили передать? Оверинженеринг немного)

2020-11-16 10:44 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +## С недоступными датами
Проблема "перехода" через выключенную дату не пофикшена. Договаривались, что если что-то выбрано слева от выключенной даты, а потом происходит выбор любой даты справа - то выбранное слева скидывается и выбор интервала начинается заново.

2020-11-16 10:45 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +            ({ handleChange, startDate, endDate }) =>
Все еще непонятно, как компонент "сверху" будет такое обрабатывать.

2020-11-16 14:06 UTC, jekatigr requested changes

2020-11-16 14:06 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Month/Month.test.tsx
> +const { goToPreviousMonths, goToNextMonths } = props;
Так нельзя делать. Каждый тест должен быть изолирован. Если во все тесты прокидывать одни и те же fn, то они будут загрязненными. Можно в handlers тесты местами поменять - они должны упасть, а такого быть не должно. Задавать jest.fn() выше норм, но в тестах для колбэков должно быть свое локальное создание этих пропсов.

2020-11-16 14:07 UTC, jekatigr commented on packages/ui-core/package.json
>        }
И состояние нажатой лкм должно быть таким же, как hover, как я понимаю.

2020-11-16 14:09 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.docz.tsx
> +const wrapperStyles = {
Может не надо задавать стили тултипа? Просто я все еще продолжал думать, что у календаря есть подложка и тень, хотя это демо-обертка.

2020-11-16 14:10 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.docz.tsx
> +export const WithBlockedDates = ({ children }) => (
Все компоненты из доки (не относящиеся к api либы) должны быть с префиксом Demo

2020-11-17 08:17 UTC, Rakot1234 commented on packages/ui-core/src/components/Calendar/doc/Calendar.docz.tsx
> +        currentEndDate !== null && setTo(formatDate(currentEndDate, 'dd.MM.yyyy'));
Не понял сути замечания, хендлер никак не влияет на работу самого компонента, он просто показывает как извне с ним взаимодействовать, меняя только заголовок надо ним, отображающий выбранные даты

2020-11-17 08:19 UTC, Rakot1234 commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +            ({ handleChange, startDate, endDate }) =>
Не понимаю сути комментария, в коллбеке возвращается теперь только реально выбранная дата, если дважды кликнуть на одну, вернется только startDate

Нужно это как-то дополнительно описать ?

2020-11-17 10:10 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +            ({ handleChange, startDate, endDate }) =>
Ну компоненту выше нужно будет получить период, но визуально период (как выше на скрине) может не совпадать с выбранным, что не правильно. Предположу, что нужно в обертке скидывать дату окончания периода.

2020-11-17 10:11 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.docz.tsx
> +        currentEndDate !== null && setTo(formatDate(currentEndDate, 'dd.MM.yyyy'));
Ну тут обертка для демонстрации, мешающая восприятию функционала компонента, т.к. сейчас нельзя понять, когда именно меняется endDate. Думаю правильнее убрать проверки.

2020-11-18 13:02 UTC, jekatigr requested changes

2020-11-18 13:02 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/Calendar.tsx
> +        switch (true) {
Тут сложно разобраться, какая ветка за что отвечает. Может разобрать это на логические переменные с говорящими названиями?

2020-11-18 16:35 UTC, Rakot1234 commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +            <div style={{margin: 'auto', maxWidth: '320px'}}>
Без переменных совсем не получится, т.к. нужно передавать текущие год и месяц, иначе заблоченные даты не попадут в поле видимости

2020-11-18 17:13 UTC, Rakot1234 commented on packages/ui-core/src/components/Calendar/Calendar.tsx
> +                isPrevMonthDisabled={String(month + 1) === minBookingMonth}
![image](https://user-images.githubusercontent.com/26911391/99563624-7fe11980-29da-11eb-81fc-63535c75b4f1.png)

Проверил - работает

2020-11-19 11:09 UTC, jekatigr requested changes

2020-11-19 11:09 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/Calendar.tsx
> +        const isCliclBeforeStartDate = stateStartDate && isEndChose && !isAfter(date, stateStartDate || 0);
```suggestion
        const isClickBeforeStartDate = stateStartDate && isEndChose && !isAfter(date, stateStartDate || 0);
```

2020-11-19 11:46 UTC, merged