feat(table): add new component
MegafonWebLab/megafon-ui pull request #416
Opened 2020-11-27 16:16 UTC by n-ilyin

2020-12-07 14:25 UTC, Gashaal requested changes

2020-12-07 14:25 UTC, Gashaal commented on packages/ui-shared/src/components/Table/Table.less
> +        display: grid;
а зачем grid?

2020-12-07 14:54 UTC, n-ilyin commented on packages/ui-shared/src/components/Table/Table.less
> +        display: grid;
Чтобы расположить тени сверху и слева, а градиенты справа и снизу относительно таблицы. Чтобы sticky на тенях и градиентах работал, нужно чтобы они были прямыми потомками scroll, как и сама таблица, без грида тень слева и градиент справа не будут оставаться на своих местах во время переполнения при других раскладках.

2020-12-08 15:33 UTC, Gashaal approved these changes

2020-12-08 15:33 UTC, merged