8550 partners
MegafonWebLab/megafon-ui pull request #419
Opened 2020-12-01 15:04 UTC by n-ilyin

2020-12-02 11:34 UTC, bashmakovartur commented on packages/ui-shared/src/components/Partners/doc/Partners.docz.tsx
> +export const twelveItems = generateItems(12, '#');
Может в доку еще добавить вариант с нечетным количеством тайлов?

2020-12-03 12:10 UTC, n-ilyin commented on packages/ui-shared/src/components/Partners/doc/Partners.docz.tsx
> +export const twelveItems = generateItems(12, '#');
Не думаю, в макете прямым текстом написано, что не рекомендуется использовать нечетное количество, а мы возьмем и покажем в доке)

2020-12-13 13:09 UTC, Gashaal requested changes

2020-12-13 13:09 UTC, Gashaal commented on packages/ui-core/src/components/Carousel/Carousel.less
> +            padding-left: 20px !important;
!important точно нужен?

2020-12-14 12:19 UTC, n-ilyin commented on packages/ui-core/src/components/Carousel/Carousel.less
> +            padding-left: 20px !important;
Да, эти отступы нужны на десктопе, чтобы не обрезалась тень у плиток. important добавлен, чтобы при переопределении контентных отступов на мобильных с помощью доп класса, когда происходит растягивании карусели на всю ширину страницы, площадка случайно не затерла эти стили.

2020-12-18 09:32 UTC, Gashaal approved these changes

2020-12-18 11:14 UTC, Gashaal approved these changes

2020-12-18 11:15 UTC, merged