feat(card): added new component
MegafonWebLab/megafon-ui pull request #421
Opened 2020-12-02 08:14 UTC by VinokurovAlexander

2020-12-02 10:09 UTC, jekatigr commented on packages/ui-shared/src/components/Card/doc/Card.example.mdx
> +```javascript
Это же не блок кода?)

И нужно добавить листинг DemoWrapper и остальных параметров, сейчас ничего не понятно из примера. Передаются какие-то пропсы, но какие...

2020-12-02 14:50 UTC, n-ilyin commented on packages/ui-shared/src/components/Card/Card.less
> +    width: 360px;
Ширину компонента нужно убрать, она должна определяется родителем

2020-12-02 15:01 UTC, n-ilyin commented on packages/ui-shared/src/components/Card/Card.tsx
> +    }, [link]);
link здесь не используется, но есть в зависимостях, и наоборот isCardLink используется, но нет в зависимостях

2020-12-02 15:02 UTC, n-ilyin commented on packages/ui-shared/src/components/Card/Card.tsx
> +    ), [button]);
Для чего button в зависимостях?

2020-12-02 15:03 UTC, n-ilyin commented on packages/ui-shared/src/components/Card/Card.tsx
> +    }, [imageSrc, svgSrc]);
objectFit тоже должен быть в зависимостях

2020-12-02 15:12 UTC, n-ilyin commented on packages/ui-shared/src/components/Card/Card.less
> +    }
Для чего этот огород с абсолютным позиционированием? Почему просто в Link не класть содержимое, если href передан?

2020-12-02 15:17 UTC, n-ilyin commented on packages/ui-shared/src/components/Card/Card.test.tsx
> +import { title, text, img, svg, button, link, fakeLink } from './doc/Card.docz';
Не уверен стоит ли все это брать из docz, это делает тесты зависимыми от демо страницы и в результате правок документации будут меняться снэпшоты

2020-12-02 15:23 UTC, n-ilyin commented on packages/ui-shared/src/components/Card/Card.less
> +    &__pic-wrapper img {
Почему через img, а не через класс?

2020-12-02 15:51 UTC, n-ilyin commented on packages/ui-shared/src/components/Card/doc/Card.example.mdx
> +</Playground>
Нужно использовать Grid для примеров

2020-12-02 15:54 UTC, n-ilyin commented on packages/ui-shared/src/components/Card/Card.less
> +        }
Это что то очень странное, любой элемент в блоке с модификатором href должен иметь тень при наведении

2020-12-02 16:00 UTC, n-ilyin commented on packages/ui-shared/src/components/Card/Card.tsx
> +    const isRenderImage = !!imageSrc || !!svgSrc;
Эта переменная не имеет смысла, т.к. renderImage и так вернет nul и ничего не отрендеритl, если не будут переданы оба параметра

2020-12-13 14:23 UTC, Gashaal requested changes

2020-12-13 14:23 UTC, Gashaal commented on packages/ui-shared/src/components/Card/Card.test.tsx
> +    it('render with one interactive element', () => {
Стоит добавить тест, в котором рендерить только ссылку.

2020-12-13 14:23 UTC, Gashaal commented on packages/ui-shared/src/components/Card/doc/Card.example.mdx
> +### Если в компонент не добавлены кнопка и ссылка, то в параметрах самой карточки должна быть указана ссылка.В таком случае карточка становится кликабельной и имеет hover состояние. Чтобы обозначить
поведениекарточки - нужно добавить пробел

2020-12-13 14:23 UTC, Gashaal commented on packages/ui-shared/src/components/Card/doc/Card.example.mdx
> +                <Header as="h2" hAlign="center" margin>Только ссылка</Header>
С "ложной ссылкой"

2020-12-16 08:11 UTC, Gashaal approved these changes

2020-12-16 08:11 UTC, merged