feat(component): add carouselblock component
MegafonWebLab/megafon-ui pull request #422
Opened 2020-12-02 10:57 UTC by astranavt

2020-12-03 14:54 UTC, n-ilyin commented on packages/ui-shared/src/components/CarouselBlock/CarouselBlock.tsx
> +const CarouselBlock: React.FC<ICarouselBlock> = ({ children, ...props }) => (
Давай назовем CarouselBox, у нас все компоненты конструктора, которые являются обертками для ui компонентов имеют Box в названии

2020-12-03 14:58 UTC, n-ilyin commented on packages/ui-shared/src/components/CarouselBlock/CarouselBlock.test.tsx
> +            <CarouselBlock>
Мне все таки кажется, что нужно делать снэпшот со всеми переданными пропсами, это может помочь в том случае, если в будущем кто то накосячит со спрэдом пропсов и тесты ничего об этом не сообщат.

2020-12-03 15:08 UTC, n-ilyin commented on packages/ui-shared/src/components/CarouselBlock/CarouselBlock.tsx
> +export interface ICarouselBlock {
Стоит вытащить типы из самого компонента, чем дублировать, иначе при изменении интерфейса в Carousel придется править в двух местах
`type ICarouselBlock = React.ComponentProps<typeof Carousel>;`

2020-12-03 15:21 UTC, n-ilyin commented on packages/ui-shared/src/components/CarouselBlock/CarouselBlock.tsx
> +};
По идее их можно не указывать, т.к. propTypes из Carousel сами выведут предупреждение в консоль, если передать параметр не того типа.

2020-12-10 08:07 UTC, Gashaal requested changes
В таких обертках решили импортировать типы.
Не дублировать документацию, а указать, что это обертка над компонентом.
Стоит посмотреть обертку над табами - https://github.com/MegafonWebLab/megafon-ui/pull/433/files и сделать по аналогии.

2020-12-10 08:07 UTC, Gashaal commented on packages/ui-shared/src/components/CarouselBox/CarouselBox.tsx
> +export interface ICarouselBox {
Можнол использовать props из карусели - type CarouselPropsTypes = React.ComponentProps<typeof Carousel>;

2020-12-10 08:07 UTC, Gashaal commented on packages/ui-shared/src/components/CarouselBox/CarouselBox.tsx
> +CarouselBox.propTypes = {
Можно убрать

2020-12-10 08:07 UTC, Gashaal commented on packages/ui-shared/src/components/CarouselBox/doc/CarouselBox.example.mdx
> +## Использование со значениями свойств заданными по умолчанию
Нужно добавить, что это обертка над компонентом Carousel

2020-12-13 15:45 UTC, Gashaal requested changes
Нужно указать carouselbox вместо component в сообщениях ко всем коммитам

2020-12-17 14:16 UTC, Gashaal approved these changes

2020-12-17 14:16 UTC, merged