refactor(videobanner): added fixes
MegafonWebLab/megafon-ui pull request #429
Opened 2020-12-04 10:06 UTC by VinokurovAlexander

Remove ContentArea from component, fix hooks dependences, edit background image and wrapper

BREAKING CHANGE: desktop image prop is not required

2020-12-04 17:50 UTC, n-ilyin commented
Давай так сделаем для src iframe
`                const url = `https://www.youtube.com/embed/${videoSrc}?`;
                const autoplay = `&autoplay=${isAutoplay ? 1 : 0}`;
                const mute = `&mute=${isMuted ? 1 : 0}`;
                const loop = `&loop=1`;
                const rel = `&rel=0`;
                const controls = `&controls=0`;
                const showInfo = `&showinfo=0e`;
                const policy = `&iv_load_policy=3`;
                const plyalist = `&playlist=${videoSrc}`;

                const src = `${url}${autoplay}${mute}${loop}${rel}${controls}${showInfo}${policy}${plyalist}`;`

2020-12-12 14:27 UTC, Gashaal requested changes

2020-12-12 14:27 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.less
> +            padding-left: 80px;
https://www.figma.com/file/pdlMZ3xqKFBc8IWyCLqfd3/%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80_%D0%92%D1%91%D1%80%D1%81%D1%82%D0%BA%D0%B0?node-id=342%3A2610 - актуальный макет? Добавь ссылку на него в задачу pls.

2020-12-12 14:27 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.less
> +            padding-right: 80px;
![image](https://user-images.githubusercontent.com/11842111/101986128-184a8100-3c9d-11eb-9eea-2b2c9e7b29f0.png)
Баннер же должен растягиватся до 1440px?

2020-12-14 14:16 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.less
> +            padding-right: 80px;
Здесь были паддинги, которые предназначены для контента, перенёс их в соответствующий блок. И добавил видео с шириной побольше

2020-12-17 09:59 UTC, Gashaal approved these changes

2020-12-17 11:13 UTC, Gashaal approved these changes

2020-12-17 11:13 UTC, merged