feat(instructions): add component
MegafonWebLab/megafon-ui pull request #440
Opened 2020-12-10 14:32 UTC by bashmakovartur

N

2020-12-10 15:17 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/Instructions.less
> +    &__title_extension_mobile {
Может resolution?

2020-12-10 15:20 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/Instructions.less
> +            background: url('./img/blackIphone.png') 50% no-repeat;
blackIphone.png применяется ко всем трем модификаторам?

2020-12-10 15:26 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/Instructions.less
> +    &__img-wrapper_mask_android {
Подобные модификаторы лучше вешать на корень, чтобы не привязывать жестко @{b}__device-screen к &__img-wrapper. В будущем рефакторинг будет проще, если понадобится, например, перемещать элементы в пределах блока, иначе придется переделывать селекторы, переносить модификаторы и т.д.

2020-12-10 15:33 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/Instructions.tsx
> +    pictureAlign= PictureAlignEnum.LEFT,
Нужно писать значение 'left', чтобы в доке было видно

2020-12-10 15:33 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/Instructions.tsx
> +    pictureMask = PictureMaskEnum.NONE,
Тоже самое

2020-12-10 15:35 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/Instructions.tsx
> +    const renderDesktopArticles = (): JSX.Element => (
useCallback

2020-12-10 15:35 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/Instructions.tsx
> +    const renderMobileArticles = (): JSX.Element => (
useCallback

2020-12-10 15:36 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/Instructions.tsx
> +    }, []);
Не указан handleResize в зависимостях

2020-12-10 15:40 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/types.ts
> +export enum PictureAlignEnum {
С enum будут проблемы при использовании на проекте, т.к. интерфейс компонента не пропустит значения, а импортировать типы из библиотеки сейчас нет возможности. В компоненте Button есть примеры решения этой проблемы.

2020-12-10 15:42 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/dok/Instructions.example.mdx
> +## Использование с изображением справа
Слово "Использование" теряет смысл если повторяется везде, лучше его вообще убрать

2020-12-10 15:44 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/dok/Instructions.example.mdx
> +## Базовое использование
Нужно показать здесь код используемых переменных из Instructions.docz.tsx, иначе непонятно что там в примерах передается

2020-12-10 16:00 UTC, n-ilyin commented
Почему то нет изменений в yarn.lock, несмотря на установленный пакет gulp-imagemin

2020-12-10 16:07 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/Instructions.test.tsx
> +describe('<Instructions />', () => {
Нет теста на рендер для разных разрешений. Кажется ресайз можно эмулировать в тестах

2020-12-10 16:17 UTC, n-ilyin commented
Изображения типа 1.png или 2.png нужны только для доки? Тогда они должны лежать в папке doc

2020-12-10 16:18 UTC, n-ilyin commented on packages/ui-shared/src/components/Instructions/dok/Instructions.mdx
> +---
Опечатка в пути, не dok, а doc

2020-12-14 08:32 UTC, bashmakovartur commented on packages/ui-shared/src/components/Instructions/Instructions.less
> +            background: url('./img/blackIphone.png') 50% no-repeat;
Ага, переделал

2020-12-18 11:22 UTC, Gashaal requested changes

2020-12-22 08:27 UTC, Gashaal approved these changes

2020-12-22 08:27 UTC, merged