8730 cards box
MegafonWebLab/megafon-ui pull request #456
Opened 2020-12-18 11:00 UTC by VinokurovAlexander

2020-12-18 13:40 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/Container/Container.less
> +@k15: e('.mfui-beta-banner-box');
k15 это у нас ссылки для скачивания, [тут](https://github.com/VinokurovAlexander/megafon-ui/commit/ae2c4580c733029d9577703b890ed0785c6fccb0) поправил

2020-12-22 11:32 UTC, bashmakovartur commented on packages/ui-shared/src/components/CardsBox/CardsBox.tsx
> +import { SlidesSettingsType } from '@megafon/ui-core/dist/es/components/Carousel/Carousel';
Я бы не экспортировал из сборки, можно что-то вроде такого:
`type SlidesSettingsType = Pick<React.ComponentProps<typeof Carousel>, 'slidesSettings'>['slidesSettings'];`

2020-12-22 11:32 UTC, bashmakovartur commented on packages/ui-shared/src/components/CardsBox/CardsBox.tsx
> +const THROTTLE_TIME = 750;
Не много? откуда такое значение?

2020-12-22 11:32 UTC, bashmakovartur commented on packages/ui-shared/src/components/CardsBox/CardsBox.tsx
> +    ), []);
Надо children добавить в зависимости

2020-12-22 11:32 UTC, bashmakovartur commented on packages/ui-shared/src/components/CardsBox/CardsBox.tsx
> +    ), []);
Тут тоже

2020-12-22 11:32 UTC, bashmakovartur commented on packages/ui-shared/src/components/CardsBox/CardsBox.test.tsx
> +});
Для мобильного разрешения теста нет.

2020-12-22 11:32 UTC, bashmakovartur commented on packages/ui-shared/src/components/CardsBox/CardsBox.tsx
> +    children: Array<React.ReactElement<ICard>> | React.ReactElement<ICard>;
`children` в любом случае будет массив

`children: Array<React.ReactElement<ICard>>;`

2020-12-22 11:32 UTC, bashmakovartur commented on packages/ui-shared/src/components/CardsBox/doc/CardsBox.example.mdx
> +# Базовое использование
В примера карточки обрезаются, стоит поправить

2020-12-25 12:08 UTC, bashmakovartur commented on packages/ui-shared/src/components/CardsBox/CardsBox.tsx
> +export default CardsBox;
При ресайзе страницы возникает ошибка: 
![Screenshot from 2020-12-25 15-07-38](https://user-images.githubusercontent.com/19557298/103134563-0fa57200-46c3-11eb-9f8d-80b8dbbbf61b.png)

2021-01-12 13:38 UTC, Gashaal requested changes

2021-01-12 13:38 UTC, Gashaal commented on packages/ui-shared/src/components/CardsBox/CardsBox.test.tsx
> +        jest.restoreAllMocks();
Стоит перенести в `afterAll`

2021-01-13 11:47 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +import ThrottleTime from '../../constants/throttle-time';
может тогда перенести этот файл в ui-core и использовать его ещё в карусели?

https://github.com/MegafonWebLab/megafon-ui/blob/07b1b2a4fe1aca50e2c63d9f87d7d61e6b350ce1/packages/ui-core/src/components/Carousel/Carousel.tsx#L167-L178

2021-01-13 12:23 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/CardsBox/CardsBox.test.tsx
> +        jest.restoreAllMocks();
Речь про `restoreAllMocks`? Похоже, что этот вызов тут не нужен. Он ведь работает для моков, которые объявлены через `spyOn` https://jestjs.io/docs/en/jest-object#jestrestoreallmocks

2021-01-14 11:20 UTC, Gashaal commented on packages/ui-shared/src/components/BenefitsPictures/BenefitsPictures.tsx
> +import ThrottleTime from '../../constants/throttle-time';
ok

2021-01-14 11:48 UTC, Gashaal commented on packages/ui-shared/src/components/CardsBox/CardsBox.test.tsx
> +        jest.restoreAllMocks();
Да, стоит удалить тогда

2021-01-14 15:15 UTC, Gashaal approved these changes

2021-01-14 15:32 UTC, merged