feat(counter): added classes prop, edit value change
MegafonWebLab/megafon-ui pull request #473
Opened 2021-01-19 12:40 UTC by VinokurovAlexander

2021-02-04 12:50 UTC, Gashaal requested changes

2021-02-04 12:50 UTC, Gashaal commented on packages/ui-core/src/components/Counter/Counter.test.tsx
> +    classes: {
Обработчики для кнопок и инпута нужны для разметки?

2021-02-04 12:50 UTC, Gashaal commented on packages/ui-core/src/components/Counter/Counter.tsx
> +    const handleValueChange = React.useCallback(
поговорил со Стасом  - нужно оставить старое поведение со валидацией по onBlur.
Можно использовать в таком виде (с onBlur) на площадке

2021-02-08 15:25 UTC, VinokurovAlexander commented on packages/ui-core/src/components/Counter/Counter.test.tsx
> +    classes: {
да, для разметки

2021-02-08 15:26 UTC, VinokurovAlexander commented on packages/ui-core/src/components/Counter/Counter.tsx
> +    const handleValueChange = React.useCallback(
Андрей тоже не против

2021-02-09 11:51 UTC, Gashaal approved these changes

2021-02-09 11:51 UTC, merged