feat(videobanner): added content text color prop, added image props f…
MegafonWebLab/megafon-ui pull request #488
Opened 2021-02-04 11:38 UTC by VinokurovAlexander

…or all resolutions

BREAKING CHANGE: Removed image prop as an object. Added separate image props for each resolution.

2021-02-05 11:16 UTC, bashmakovartur commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
>      isMuted?: boolean;
Этот пропс не протестирован никак

2021-02-08 08:42 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +                <Button className={cn(ClassName.BUTTON)} href={href} onClick={onButtonClick}>{buttonTitle}</Button>
нужен prettier)

2021-02-08 11:06 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +    imageDesktopWide?: string;
Да, на десктопе может быт либо картинка, либо видео.

2021-02-09 08:42 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +    imageDesktopWide?: string;
Стоит добавить в инструкцию для км-в, что нужно задавать либо видео, либо картинки.

2021-02-09 08:45 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +    imageDesktopWide?: string;
Стоит добавить в инструкцию для км-в, что нужно задавать либо видео, либо картинки.

2021-02-09 08:59 UTC, Gashaal requested changes

2021-02-09 08:59 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx
> +            expect(mutedProp).toBeFalsy();
Почему тут и ниже не использовать toMatchSnapshot?

2021-02-09 08:59 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx
> +    textColor: TextColor.CLEAR_WHITE,
Стоит добавить тест на `FRESH_ASPHALT`

2021-02-09 08:59 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.example.mdx
>  ## Только изображение
Стоит дописать, что если не указывать videoSrc, то нужно указать картинки для всех разрешений.

2021-02-10 08:20 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx
> +            expect(mutedProp).toBeFalsy();
В этих тестах происходят незначительные изменения по вёрстке и я подумал, что делать ради этого снэпшот чересчур. Мне кажется очевиднее будет прочитать такой код и понять, что он тестирует, чем вглядываться в снэпшот и искать какое свойство, атрибут или класс поменялся у dom элемента.

2021-02-10 08:20 UTC, VinokurovAlexander commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.tsx
> +    imageDesktopWide?: string;
ок

2021-02-10 09:56 UTC, Gashaal commented on packages/ui-shared/src/components/VideoBanner/VideoBanner.test.tsx
> +            expect(mutedProp).toBeFalsy();
Да, в этом есть смысл. Но нам нужно понять, в каких случаях мы делаем снепшоты, а в каких проверяем конкретные пропсы, свойства и пр. Предлагаю обсудить это отдельно и как-то формализовать, но тут пока сделать снепшоты.

2021-02-10 12:11 UTC, Gashaal approved these changes

2021-02-10 12:11 UTC, merged