test(tooltip): added tests
MegafonWebLab/megafon-ui pull request #500
Opened 2021-02-16 11:18 UTC by tasty-tasty

2021-02-16 12:46 UTC, jekatigr requested changes

2021-02-16 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.test.tsx
> +            expect(wrapper.find(openedTooltipClassName)).toHaveLength(1);
100, 111 и 122 строки можно проверить скопом через один снепшот. Точнее зафиксировать. Ну либо в одном тест-кейсе их проверить, незачем размазывать.

2021-02-16 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.test.tsx
> +            const tooltipNode = wrapper.find(tooltipClassName).getDOMNode();
Можно вынести в функцию.

```
const dispatchEvent = async (wrapper: ShallowWrapper | ReactWrapper, event: MouseEvent, targetClass: string) => {
                const node = wrapper.find(targetClass).getDOMNode();

                await act( async () => {
                    node.dispatchEvent(event);
                });
                wrapper.update();
            };

            await dispatchEvent(wrapper, mouseOverEventBubbles, tooltipClassName);
```

2021-02-16 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.test.tsx
> +const TestTooltipWrapper = ({ isOpen = false, children }) => {
Лучше эту обертку перенести к тест-кейсам, где она используется. А в TestTooltipWithHandlers ее не использовать. Потому что сейчас из-за вложенности сложно разобраться в флоу тест-кейсов.

2021-02-16 12:46 UTC, jekatigr commented on packages/ui-core/src/components/Tooltip/Tooltip.test.tsx
> +                            <div className="open-button" onClick={handleOpen} />
Вообще, можно не создавать в тесткейсе кнопки, которые предназначены только для изменения пропсов тултипа. Это лишняя сущность. Мне кажется можно напрямую пропсы менять.

2021-02-16 13:43 UTC, tasty-tasty commented on packages/ui-core/src/components/Tooltip/Tooltip.test.tsx
> +            expect(wrapper.find(openedTooltipClassName)).toHaveLength(1);
Объединю в один тест кейс, без снепшота т.к. используется mount и изменения в используемом компоненте Tile внутри могут поменять снепшот

2021-02-16 13:53 UTC, tasty-tasty commented on packages/ui-core/src/components/Tooltip/Tooltip.test.tsx
> +                            <div className="open-button" onClick={handleOpen} />
Ок, но в enzyme можно менять props только на wrapper, попробую пересмотреть подход.

2021-08-04 13:20 UTC, tasty-tasty commented
deprecated

2021-08-04 13:20 UTC, closed without merging