9161 add lists by html
MegafonWebLab/megafon-ui pull request #507
Opened 2021-02-25 12:29 UTC by bashmakovartur

2021-03-01 07:58 UTC, astranavt commented on packages/ui-core/src/utils/convert.tsx
>  type ConfigItem = {
Абстрактное название типа, может быть назвать TransformElement ?

2021-03-01 07:59 UTC, astranavt commented on packages/ui-core/src/utils/convert.tsx
>  export type Config = {
Абстрактный Config, предлагаю назвать TransformConfig

2021-03-01 08:17 UTC, astranavt commented on packages/ui-core/src/utils/convert.tsx
>              const Component = config[node]?.component;
Предлагаю такой вариант:

```TypeScript
 const nodeElement = config[node];

            if (nodeElement) {
                const { component: Component, className } = nodeElement;
                const filteredProps = {
                    key: transformProps.key,
                    className: className || ""
                };

                nodeElement.props?.forEach(prop => {
                    if (transformProps[prop] !== undefined) {
                        filteredProps[prop] = transformProps[prop];
                    }
                });

                return <Component {...filteredProps}>{children}</Component>;
            }

            return null;
```

2021-03-01 08:21 UTC, astranavt commented on packages/ui-core/src/utils/convert.tsx
>              const Component = config[node]?.component;
Предлагаю такой вариант:
```Typescript
         const nodeElement = config[node];

            if (nodeElement) {
                const { component: Component, className } = nodeElement;
                const filteredProps = {
                    key: props.key,
                    className: className || ""
                };

                nodeElement.props?.forEach(prop => {
                    if (props[prop] !== undefined) {
                        filteredProps[prop] = props[prop];
                    }
                });

                return <Component {...filteredProps}>{children}</Component>;
            }

            return null;
```

2021-03-01 08:24 UTC, astranavt commented on packages/ui-shared/src/components/BenefitsIcons/BenefitsIconsTile.tsx
> +const typographyConfig = {
В данной переменной лежат правила трансформации тегов в компоненты, предлагаю назвать переменную `convertRules`

2021-03-01 08:45 UTC, astranavt commented on packages/ui-shared/src/components/BenefitsIcons/BenefitsIconsTile.tsx
> +    convert as modifiedConvert
Не очевидно что делает modifiedConvert, предлагаю заменить на `htmlToReactComponent` ?

2021-03-03 09:07 UTC, Gashaal requested changes

2021-03-03 09:07 UTC, Gashaal commented on packages/ui-shared/src/components/BenefitsIcons/BenefitsIconsTile.tsx
> +const typographyConfig = {
тогда уж `transformRules` для консистентности

2021-03-04 08:58 UTC, Gashaal approved these changes

2021-03-04 08:59 UTC, merged