feat(calendar): changed dates chose behaviour and added hover
MegafonWebLab/megafon-ui pull request #530
Opened 2021-03-22 17:03 UTC by Rakot1234

2021-03-23 12:16 UTC, jekatigr requested changes

2021-03-23 12:16 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Day/Day.test.tsx
> +        it('renders Day with all props', () => {
Нужно проверить, что выше рендерятся только обязательные пропсы, а тут уже все.

2021-03-23 12:16 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/Calendar.tsx
> +    const checkDateStatus = (date: Date): boolean => {
checkDateStatus -> isDateHighlighted

или типа того. Общий статус вообще непонятно о чем.

2021-03-23 12:16 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/Calendar.tsx
> +        return !!stateStartDate && !!hoveredDate && isAfter(hoveredDate, date) && isBefore(stateStartDate, date);
Думаю еще правильно показывать "уменьшение диапазона". Т.е. если выбрать период с 1 по 10, а потом навестись на 3, то должен подсвечиваться период с 3 по 10. Кажется в текущей реализации это логично.

2021-03-23 12:16 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Day/Day.tsx
> +        between: isBetween || (isSelected && !isSelectedStartOrEnd),
Сейчас при выборе первой даты и переносе ховера на следующие даты подсветка мелькает. Может можно поправить верстку так, чтобы блоки дня в календаре шли вплотную, чтобы избежать малькания?

2021-03-23 17:45 UTC, Rakot1234 commented on packages/ui-core/src/components/Calendar/Calendar.tsx
> +        return !!stateStartDate && !!hoveredDate && isAfter(hoveredDate, date) && isBefore(stateStartDate, date);
Уменьшение диапазона показать невозможно, потому что цвет выделения при ховере более яркий, чем цвет выбранного периода, он показывается, просто незаметен

Теоретически можно сделать чтобы та выбранная часть периода, которая обрежется, становилась светлее, но это нам сейчас очень усложнит логику, которая уже многовато, возможно оставить это до окончательного согласования функционала, чтобы потом не вырезать это все/править ?

Не забыть только пометить себе что этот момент надо обсудить)

2021-03-24 09:41 UTC, jekatigr requested changes

2021-03-24 09:41 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Day/Day.less
>  @{b} {
Ховер над днем отображается криво.

2021-03-24 09:41 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Day/Day.less
> +    position: relative;
В режиме выбора одного дня период подсвечиваться не должен.

2021-03-24 09:41 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Day/Day.less
>      .small();
В примере с недоступными датами некорректно показывается период. 
Кейс: выбираем 10 число, при этом с 20 включительно даты недоступны. Если навести курсор на 20, а затем на 19, то подсветка периодна не появится.

2021-03-24 13:32 UTC, merged