feat(container): added enable/disable padding top and bottom
MegafonWebLab/megafon-ui pull request #546
Opened 2021-04-02 10:45 UTC by astranavt

2021-04-05 06:53 UTC, bashmakovartur commented on packages/ui-shared/src/components/Container/Container.tsx
> +    /** Отключает отступ сверху */
Лучше написать более нейтрально - "Отключить отступ сверху".
Про disablePaddingBottom так же.

2021-04-05 06:53 UTC, bashmakovartur commented on packages/ui-shared/src/components/Container/Container.test.tsx
> +    disablePaddingBottom: true,
Надо в propTypes еще добавить.

2021-04-05 15:42 UTC, Gashaal requested changes

2021-04-05 15:42 UTC, Gashaal commented on packages/ui-shared/src/components/Container/doc/Container.example.mdx
> +    <Container disablePaddingTop={true} disablePaddingBottom={true}>
У первого контейнера и так нет верхнего отступа, может задать disablePaddingTop={true} disablePaddingBottom={true} второму контейнеру?

2021-04-08 10:30 UTC, Gashaal approved these changes

2021-04-08 10:30 UTC, merged