feat(picturewithdescription): add prop istexttopalign
MegafonWebLab/megafon-ui pull request #548
Opened 2021-04-02 12:32 UTC by bashmakovartur

2021-04-03 08:03 UTC, astranavt commented on packages/ui-shared/src/components/PictureWithDescription/PictureWithDescription.tsx
> +    /** Выравнивание текста во верхнему краю */
/** Выравнивание текста По верхнему краю */

2021-04-05 15:58 UTC, Gashaal requested changes

2021-04-05 15:58 UTC, Gashaal commented on packages/ui-shared/src/components/PictureWithDescription/PictureWithDescription.less
> +            align-self: end;
Почему end? нужно же выровнять по верху

2021-05-12 13:05 UTC, Gashaal approved these changes

2021-05-12 13:05 UTC, merged