feat(tooltip): new props and design
MegafonWebLab/megafon-ui pull request #579
Opened 2021-05-17 13:39 UTC by IggyStooges

2021-05-17 14:16 UTC, jekatigr requested changes

2021-05-17 14:16 UTC, jekatigr commented on packages/ui-core/src/components/Notification/Notification.tsx
> +    type = NotificationTypes.SUCCESS,
Значения по-умолчанию нужно задавать в виде строк, т.к. иначе дока не подтягивает нужное значение.

2021-05-17 14:16 UTC, jekatigr commented on packages/ui-core/src/components/Notification/doc/Notification.example.mdx
> +## Нотификации с цветным фоном
Думаю правильнее не в два примера все возможножные вариации запихнуть, а идти более "гранулярно", плюс-минус 1 пропс = 1 пример.

2021-05-17 14:18 UTC, jekatigr commented on packages/ui-core/src/components/Notification/doc/Notification.example.mdx
> +        ></Notification>
```suggestion
        />
```
Дочерних же нет.

2021-05-17 14:19 UTC, jekatigr commented on packages/ui-core/src/components/Notification/doc/Notification.example.mdx
> +        onClose={() => {alert('Обработчик закрытия')}}
Не надо алертов в демках. Это неудобно. Лучше обернуть в обертку, где выводить что-то типа "количество кликов"

2021-05-17 14:20 UTC, jekatigr commented on packages/ui-core/src/components/Notification/doc/Notification.example.mdx
>      <div style={marginBottom}>
Может лучше гридами/флексами определить layout и в Playground его задать? Чтобы над нотификашками не было лишних оберток.

2021-05-17 14:21 UTC, jekatigr commented on packages/ui-core/src/styles/base.less
> +@311: #5BD9E5;
А зачем? В дизайн-система цвет называется 311C, не 311.

2021-05-21 14:00 UTC, jekatigr requested changes

2021-05-21 16:36 UTC, jekatigr commented on packages/ui-core/src/components/Notification/Notification.test.tsx
> +            <Notification icon={icon} content="content">Some test text</Notification>
Иконка не обязательная

```suggestion
            <Notification content="content">Some test text</Notification>
```

Но теперь нужно проверить, что проставляются правильные иконки в зависимости от type (если конечно это видно в снепе).

2021-05-24 15:05 UTC, jekatigr requested changes

2021-05-24 15:05 UTC, jekatigr commented on packages/ui-core/src/components/Notification/doc/Notification.example.mdx
> +## Различные варианты отображения компонента
Они во всех примерах выше различные)

```suggestion
## Заполнено частично
```

или 

```suggestion
## Не весь контент
```

или около того

2021-05-24 15:05 UTC, jekatigr commented on packages/ui-core/src/components/Notification/doc/Notification.example.mdx
> +      {({ initialClickAmount, onLinkClick }) =>
Здесь (и ниже) точно нужна обертка? Она ничего нового или примечательного не демонстрирует относительно предыдущих примеров.

2021-05-24 15:05 UTC, jekatigr commented on packages/ui-core/src/styles/base.less
> +@Pantone311C: #5BD9E5;
Нужно переименовать его на странице Icons видимо.

2021-05-24 15:08 UTC, jekatigr commented on packages/ui-core/src/components/Notification/doc/Notification.example.mdx
> +</Playground>
Нужен еще один пример с error с комментом, что ссылка на нем белого цвета.

2021-05-24 19:55 UTC, IggyStooges commented on packages/ui-core/src/styles/base.less
> +@Pantone311C: #5BD9E5;
наверное, имелось в виду на странице Colors)

2021-05-25 08:44 UTC, jekatigr commented on packages/ui-core/src/styles/base.less
> +@Pantone311C: #5BD9E5;
Ну, да)

2021-05-25 08:45 UTC, merged