Utils package
MegafonWebLab/megafon-ui pull request #639
Opened 2021-06-24 16:31 UTC by tasty-tasty

Extracts utils from @megafon/ui-core to independent package

2021-06-25 09:59 UTC, jekatigr requested changes

2021-06-25 09:59 UTC, jekatigr commented on packages/ui-core/src/components/Accordion/Accordion.tsx
> +import { IDataAttributes } from '@megafon/utils/dist/typings/dataAttrs';
Может экспортнуть из корня этот тип, чтобы в dist не лезть?

2021-06-25 09:59 UTC, jekatigr commented on packages/ui-core/src/components/Accordion/Accordion.tsx
> +            className={cn({ open: isOpenedState }, [className, rootPropsClasses, openedClassName])}
Это закрывает какую-то багу? Тут мр и так огромный, трогать компоненты функционально тут - явно лишнее. Нужен фокус.

2021-06-25 09:59 UTC, jekatigr commented on packages/ui-core/src/components/Banner/Banner.test.tsx
> +        wrapper.find(bannerArrowClassName).last().simulate('click');
Все изменения рефакторинга компонентов нужно убрать из этого мр-а и перенести в следующий. В этом должна остаться только структура, сборка и изменение путей импортов.

2021-06-25 09:59 UTC, jekatigr commented on packages/ui-core/src/components/Header/Header.tsx
> +    className?: string;
Зачем?

2021-06-25 09:59 UTC, jekatigr commented on packages/utils/README.md
> +
Нужно дополнить.

2021-06-25 09:59 UTC, jekatigr commented on packages/utils/rollup.config.js
> +import compileDts from './scripts/compileDts';
Точно нельзя взять rollup-plugin-dts? Очень не хотелось бы кастомное решение поддерживать.

2021-06-25 10:13 UTC, tasty-tasty commented on packages/ui-core/src/components/Accordion/Accordion.tsx
> +            className={cn({ open: isOpenedState }, [className, rootPropsClasses, openedClassName])}
Была ошибка типизации внутри компонента. После импорта cnCreate из utils, в этом месте и в других где есть правки в компонентах.

2021-06-25 10:17 UTC, tasty-tasty commented on packages/ui-core/src/components/Header/Header.tsx
> +    className?: string;
Мы вроде нигде такое не поддерживаем. Мы везде на проектах для параметра className используем cnCreate функцию, которая может принимать массив, но возвращает всегда строку

2021-06-25 10:24 UTC, tasty-tasty commented on packages/ui-core/src/components/Accordion/Accordion.tsx
> +            className={cn({ open: isOpenedState }, [className, rootPropsClasses, openedClassName])}
для `(isOpenedState && openedClass)` будет тип `string | false | undefined`, что не соответсвует ожидаемому типу в параметре функции

2021-06-25 10:48 UTC, tasty-tasty commented on packages/ui-core/src/components/Banner/Banner.test.tsx
> +        wrapper.find(bannerArrowClassName).last().simulate('click');
Для тестов ок, верну в текущем pr реализацию с импортами cnCreate и detectTouch из пакетов, но в отдельном pr лучше избавиться от таких зависимостей в тестах

2021-06-25 10:55 UTC, jekatigr commented on packages/ui-core/src/components/Banner/Banner.test.tsx
> +        wrapper.find(bannerArrowClassName).last().simulate('click');
Рефакторинг - это хорошо) Но отдельным мр-ом лучше.

2021-06-25 10:57 UTC, jekatigr commented on packages/ui-core/src/components/Header/Header.tsx
> +    className?: string;
Помню кейс на корпоративном, когда нужно в заголовок передать несколько примиксованных классов. Тогда либо строку формировать на стороне проекте, либо тут. Поэтому добавили возможность передавать массив.

2021-06-25 16:12 UTC, tasty-tasty commented on packages/ui-core/src/components/Banner/Banner.test.tsx
> +        wrapper.find(bannerArrowClassName).last().simulate('click');
Откатил файлы тестов

2021-06-25 16:12 UTC, tasty-tasty commented on packages/ui-core/src/components/Header/Header.tsx
> +    className?: string;
Вернул  тип `string[]`

2021-06-28 17:35 UTC, tasty-tasty commented on packages/utils/README.md
> +
https://github.com/MegafonWebLab/megafon-ui/pull/639/commits/348228497c93b99aa664394a78ddab3599820e3d

2021-07-05 12:18 UTC, jekatigr requested changes

2021-07-05 12:18 UTC, jekatigr commented on packages/ui-core/typings/custom-typings.d.ts
>  declare module 'classnames';
Возможно лишнее тут и в shared.

2021-07-05 12:18 UTC, jekatigr commented on gatsby-node.js
>      const constants = glob.sync('../packages/ui-core/src/constants/*.ts');
Константы с брейкпоинтами также нужно унести в utils. Названия нужно поменять и взять те, что на проектах. 
Константу trottle удалить из экспорта, для ui-shared скопипастить.

2021-07-05 12:18 UTC, jekatigr commented on packages/ui-core/gulpfile.js
> +    env: {
В env для тестов добавлять конфиг - ок. Но остальное же не от окружения зависит, а от задачи. Можно по-другому структоризовать rc-файл?

2021-07-06 10:44 UTC, tasty-tasty commented on packages/ui-core/gulpfile.js
> +    env: {
Можно поменять [babelrc для utils](https://github.com/MegafonWebLab/megafon-ui/pull/639/commits/adbb601139ac5e6e70822b124299725a47a17b63#diff-7c4ef4e087ba291a8c071e5529e86b0ef22f0bf6c703f4bc5e3cdbd9890ffc59R1) на 
```
presets: [
    '@babel/react',
    '@babel/typescript',
    ['@babel/env', {
        modules: false,
        useBuiltIns: 'usage',
        corejs: '3.6',
    }]
],
plugins: [
    '@babel/plugin-transform-object-assign',
    ['@babel/plugin-transform-runtime', {
        version: '^7.8.4',
    }]
],
env: {
    test: {
        presets: [
            ['@babel/env', {
                targets: {
                    node: '14.17.1',
                },
            }]
        ],
    },
},
```

Для ui-core и ui-shared на разных этапах сборки используются  3 разных конфига: 
1) Для модулей иконок
2) Для es модулей
3) Для commonjs модулей

в текущих условиях сборки учитывая, что конфиги применяются последовательно нужно 3 источника, это могут быть и отдельные файлы конфигов (babelrc.es.json, babelrc.common.json, babelrc.icon.json) с extend из base конфига например. 

Предлагаю решить с babelrc по пакетам в последующих pr. babelrc для сборки модулей иконок например вообще будет не нужен после задачи на распил иконок

2021-07-07 09:28 UTC, tasty-tasty commented on packages/ui-core/gulpfile.js
> +    env: {
Для core и shared вернул конфиги инлайново в gulp

2021-07-08 15:29 UTC, jekatigr commented on packages/ui-core/gulpfile.js
>                  constants: './src/constants'
Кажется, лишнее.

2021-07-08 15:36 UTC, jekatigr commented on packages/utils/package.json
> +  "sideEffects": false,
Лишнее.

2021-07-08 16:06 UTC, jekatigr commented on packages/utils/README.md
> +// block_mod
Тут ошибка

```suggestion
// block block_mod
```

Ну и ниже.

2021-07-08 16:29 UTC, tasty-tasty commented on packages/utils/README.md
> +// block_mod
исправил

2021-07-13 15:06 UTC, merged