feat(pagination): add new component
MegafonWebLab/megafon-ui pull request #647
Opened 2021-07-06 15:19 UTC by VinokurovAlexander

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/components/PaginationButton/PaginationButton.tsx
> +    theme?: 'black' | 'white';
нужно двигаться к стандартизации значений для тем. рекомендую переименовать в `'dark'` и `'light'`.

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/components/PaginationButton/PaginationButton.tsx
> +    theme = 'black',
соответственно здесь тоже `'dark'`

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/components/PaginationButton/PaginationButton.tsx
> +    theme: PropTypes.oneOf(['black', 'white']),
и здесь — `'dark', 'light'`

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/usePagination.ts
> +            const isMobile = window.innerWidth < MOBILE_RESOLUTION;
```suggestion
            const isMobile = window.innerWidth <= MOBILE_RESOLUTION;
```

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/usePagination.ts
> +            return [Button.FIRST,  Button.HIDDEN, ...range];
```suggestion
            return [Button.FIRST, Button.HIDDEN, ...range];
```

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/__tests__/usePagination.test.tsx
> +            localWindow.innerWidth = 320;
выглядит, как магическое число. стоит добавить комментарий.

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/usePagination.ts
> +const getItems = (totalPages: number, activePage: number, maxButtonsCount: number, neighbourCount: number) => {
три и более аргумента всегда уже очень сложно воспринимаются. может быть переписать в объект?

```javascript
({
    totalPages: number,
    activePage: number,
    maxButtonsCount: number,
    neighbourCount: number,
})
```

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/usePagination.ts
> +
лишняя строка

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/components/PaginationButton/PaginationButton.tsx
> +    value: PropTypes.oneOfType([ PropTypes.number, PropTypes.string ]),
```suggestion
    value: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
```

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/components/PaginationNavigation/PaginationNavigation.tsx
> +import PaginationButton from 'components/Pagination/components/PaginationButton/PaginationButton';
локальные зависимости лучше импортировать по относительному пути

```suggestion
import PaginationButton from '../PaginationButton/PaginationButton';
```

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/doc/Pagination.docz.tsx
> +    };
можно не заворачивать в отдельную функцию, а сразу передать в проп `onChange`

2021-07-07 09:46 UTC, svetogor commented on packages/ui-core/src/components/Pagination/doc/Pagination.docz.tsx
> +            onChange={handleChange}
```suggestion
            onChange={setActivePage}
```

2021-07-08 15:05 UTC, VinokurovAlexander commented on packages/ui-core/src/components/Pagination/usePagination.ts
> +            const isMobile = window.innerWidth < MOBILE_RESOLUTION;
не, `MOBILE_RESOLUTION === 360` ведь, а это уже разрешение с которого отображается 7 кнопок пагинации

2021-07-08 15:08 UTC, VinokurovAlexander commented on packages/ui-core/src/components/Pagination/components/PaginationButton/PaginationButton.tsx
> +    theme?: 'black' | 'white';
согласен, `black` и `white` как-то неполиткорректно ))

2021-07-09 11:02 UTC, svetogor approved these changes

2021-07-09 13:01 UTC, svetogor requested changes

2021-07-09 13:01 UTC, svetogor commented on packages/ui-core/src/components/Pagination/doc/Pagination.mdx
> +# Paragraph
```suggestion
# Pagination
```

2021-07-09 13:59 UTC, svetogor approved these changes

2021-07-12 13:22 UTC, merged