Icons package
MegafonWebLab/megafon-ui pull request #673
Opened 2021-08-04 13:02 UTC by tasty-tasty

Extracts source icons files and build process from @megafon/ui-core to independent package
---
TODO: 
Checked_24 icon needs to be fixed

2021-08-10 11:59 UTC, jekatigr requested changes

2021-08-10 11:59 UTC, jekatigr commented on packages/icons/src/doc/Icons.tsx
>                  <div className={cn()}>
Копирование без расширения .svg уже не актуально, нужно вырезать.

2021-08-10 11:59 UTC, jekatigr commented on packages/icons/src/doc/Icons.less
> +        border: 1px solid #EDEDED;
Можем вынести цвета в переменные? Прям в этом же файле.

2021-08-10 11:59 UTC, jekatigr commented on packages/icons/gulpfile.js
> +const cheerio = require('cheerio');
cheerio не хватает в зависимостях

2021-08-11 16:01 UTC, tasty-tasty commented on packages/icons/gulpfile.js
> +const cheerio = require('cheerio');
cheerio, svgo, htmr@1.0.0 в зависимостях ломают сборку.

Будет ошибка в .docz/public/render-page.js, похоже на проблемы c резолвом модулей в docz. Сейчас так же в master ветке нет cheerio в зависимостях для core и shared.

Может выпилим docz?  В демо сейчас используется кастомный Playground, получается что прослойка с docz не нужна, можно собирать c gatsby и gatsby-pugin-mdx 

---

#### Примеры ошибок:

**cheerio**
```TypeError: DomHandler is not a constructor

  41 |     //helper methods
  42 |     parseDOM: function(data, options) {
> 43 |         var handler = new DomHandler(options);
     | ^
  44 |         new Parser(handler, options).end(data);
  45 |         return handler.dom;
  46 |     },


  WebpackError: TypeError: DomHandler is not a constructor
  
  - index.js:43 Object.parseDOM
    node_modules/htmlparser2/lib/index.js:43:1
  
  - index.js:262 convertServer
    node_modules/htmr/lib/index.js:262:1
  
  - convert.tsx:113 convertToReact
    packages/ui-helpers/src/convert.tsx:113:25
  
  - Property.docz.tsx:22 Module.../packages/ui-shared/src/components/Property/doc/Property.docz.tsx
    packages/ui-shared/src/components/Property/doc/Property.docz.tsx:22:5
  
  - mdx-scopes.js:50 Module.../node_modules/gatsby-plugin-mdx/loaders/mdx-scopes.js
    node_modules/gatsby-plugin-mdx/loaders/mdx-scopes.js:50:16
  
  - index.esm.js:52 process.emit
    node_modules/@datepicker-react/hooks/lib/index.esm.js:52:1
  
  - index.esm.js:640 emit
    node_modules/@datepicker-react/hooks/lib/index.esm.js:640:11
  
  - index.esm.js:198 processImmediate
    node_modules/@datepicker-react/hooks/lib/index.esm.js:198:1
  
  - assertThisInitialized.js:1 doBuildPages
    node_modules/@babel/runtime/helpers/assertThisInitialized.js:1:1
  
  - defineProperty.js:7 buildHTML
    node_modules/@babel/runtime/helpers/defineProperty.js:7:1
  
  - index.esm.js:182 module.exports
    node_modules/@datepicker-react/hooks/lib/index.esm.js:182:1
```

**svgo**
```TypeError: Cannot read property 'Tag' of undefined

  30 | var domelementtype_1 = require("domelementtype");
  31 | var nodeTypes = new Map([
> 32 |     [domelementtype_1.ElementType.Tag, 1],
     | ^
  33 |     [domelementtype_1.ElementType.Script, 1],
  34 |     [domelementtype_1.ElementType.Style, 1],
  35 |     [domelementtype_1.ElementType.Directive, 1],


  WebpackError: TypeError: Cannot read property 'Tag' of undefined
  
  - node.js:32 Object.../node_modules/domhandler/lib/node.js
    node_modules/domhandler/lib/node.js:32:1
  
  - index.js:15 Object.../node_modules/domhandler/lib/index.js
    node_modules/domhandler/lib/index.js:15:14
  
  - index.js:2 Object.../node_modules/htmlparser2/lib/index.js
    node_modules/htmlparser2/lib/index.js:2:18
  
  - index.js:6 Object.../node_modules/htmr/lib/index.js
    node_modules/htmr/lib/index.js:6:30
  
  - index.esm.js:52 process.emit
    node_modules/@datepicker-react/hooks/lib/index.esm.js:52:1
  
  - index.esm.js:640 emit
    node_modules/@datepicker-react/hooks/lib/index.esm.js:640:11
  
  - index.esm.js:198 processImmediate
    node_modules/@datepicker-react/hooks/lib/index.esm.js:198:1
  
  - assertThisInitialized.js:1 doBuildPages
    node_modules/@babel/runtime/helpers/assertThisInitialized.js:1:1
  
  - defineProperty.js:7 buildHTML
    node_modules/@babel/runtime/helpers/defineProperty.js:7:1
  
  - index.esm.js:182 module.exports
    node_modules/@datepicker-react/hooks/lib/index.esm.js:182:1
```

**htmr@1.0.0**
```
TypeError: Cannot read property 'Tag' of undefined


  30 | var domelementtype_1 = require("domelementtype");
  31 | var nodeTypes = new Map([
> 32 |     [domelementtype_1.ElementType.Tag, 1],
     | ^
  33 |     [domelementtype_1.ElementType.Script, 1],
  34 |     [domelementtype_1.ElementType.Style, 1],
  35 |     [domelementtype_1.ElementType.Directive, 1],


  WebpackError: TypeError: Cannot read property 'Tag' of undefined
  
  - node.js:32 Object.../node_modules/domhandler/lib/node.js
    node_modules/domhandler/lib/node.js:32:1
  
  - index.js:15 Object.../node_modules/domhandler/lib/index.js
    node_modules/domhandler/lib/index.js:15:14
  
  - index.js:2 Object.../node_modules/htmlparser2/lib/index.js
    node_modules/htmlparser2/lib/index.js:2:18
  
  - index.js:6 Object.../node_modules/htmr/lib/index.js
    node_modules/htmr/lib/index.js:6:30
  
  - index.esm.js:52 process.emit
    node_modules/@datepicker-react/hooks/lib/index.esm.js:52:1
  
  - index.esm.js:640 emit
    node_modules/@datepicker-react/hooks/lib/index.esm.js:640:11
  
  - index.esm.js:198 processImmediate
    node_modules/@datepicker-react/hooks/lib/index.esm.js:198:1
  
  - assertThisInitialized.js:1 doBuildPages
    node_modules/@babel/runtime/helpers/assertThisInitialized.js:1:1
  
  - defineProperty.js:7 buildHTML
    node_modules/@babel/runtime/helpers/defineProperty.js:7:1
  
  - index.esm.js:182 module.exports
    node_modules/@datepicker-react/hooks/lib/index.esm.js:182:1
```

2021-08-25 14:44 UTC, merged