fix(textfield): fix value of controlled input
MegafonWebLab/megafon-ui pull request #709
Opened 2021-09-17 11:38 UTC by IggyStooges

2021-09-20 15:00 UTC, jekatigr requested changes

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +    /** Внешнее значение для контролируемого компонента, для неконтролируемеого не определяется */
```suggestion
    /** Внешнее значение для контролируемого компонента, для неконтролируемого не определяется */
```

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +    /** Первоначально заданное значение для неконтролируемого компонента, для контролируемеого не определяется  */
```suggestion
    /** Первоначально заданное значение для неконтролируемого компонента, для контролируемого не определяется  */
```

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +        const isClearFuncAvailable = !isControlled && !customIcon &&
Лучше не пользоваться переносом, а разбить на две переменные.

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +                {!inputValue && placeholder && renderPlaceholderForIe('placeholder-input')}
renderPlaceholderForIe тоже относится к ie) Тоже нужно выпилить вместе со стилями. Вообще кастомную обработку placeholder'а нужно проверить.

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +        if (!inputValue && inputParams.placeholder) {
Было сделано для ie, скорее всего теперь лишнее.

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +        if (!inputValue && textareaParams.placeholder) {
И тут.

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +                {!inputValue && placeholder && renderPlaceholderForIe('placeholder-textarea')}
И тут.

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
>  };
У нас компонент функциональный, непонятно почему тут остались дефолтные пропсы. Нужно попробовать перенести в деструкторизацию в сигнатуру.

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +            );
Кажется отступы поехали.

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +const MyPropTypes = {
```suggestion
const CustomPropTypes = {
```

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +                `The component ${componentName} need the prop 'initialValue' if uncontrolled, pass 'value' or set isControlled={false}`
Кажется текст не соответствует кейсу.

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +                `The component ${componentName} need the prop 'value' if isControlled, pass 'initialValue' prop for uncontrolled component`
Кажется текст не соответствует кейсу.

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +    value?: string | number;
Возможно, нужно задать обязательным. Лучше проверить на проекте.

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +    /** Переводит компонент в контролируемое состояние */
Строго говоря, false переводит в неконтролируемое. В следующей структуре нет комментов, т.к. они не отображаются в доке?

2021-09-20 15:00 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
>          checkSymbolMaxLimit(value);
Должен был сломаться функционал подсчета символов. Должно работать для обоих режимов компонента.

2021-09-21 06:40 UTC, IggyStooges commented on packages/ui-core/src/components/TextField/TextField.tsx
> +    /** Переводит компонент в контролируемое состояние */
да, если там добавить, они 2 раза выведутся)

2021-09-21 06:55 UTC, IggyStooges commented on packages/ui-core/src/components/TextField/TextField.tsx
> +    /** Переводит компонент в контролируемое состояние */
![изображение](https://user-images.githubusercontent.com/36813348/134125206-10cfed64-929d-47ab-a5fa-801b7c603fdc.png)
в доке норм отображается)

2021-09-22 10:05 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +        if (typeof props[propName] !== 'boolean') {
Проверка на опциональность.

2021-09-22 10:05 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +export type ITextFieldProps = ICommonProps & ValueProps;
```suggestion
export type TextFieldProps = ICommonProps & ValueProps;
```

2021-09-27 12:47 UTC, merged