Add interactive
MegafonWebLab/megafon-ui pull request #771
Opened 2021-11-24 12:01 UTC by IggyStooges

2021-11-25 08:51 UTC, jekatigr requested changes

2021-11-25 09:10 UTC, IggyStooges commented on packages/ui-core/src/components/Select/Select.tsx
> -                role="button"
просьба перепроверить.

2021-11-25 12:18 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> -                role="button"
Перепроверил. Воспроизводится при клике на поле, а не на стрелку. Если кликнуть на стрелку, то управление стрелками клавиатуры работает, но если на поле - то нет. Получается контр-интуитивно.

2021-11-25 12:19 UTC, jekatigr commented on packages/ui-core/src/components/Carousel/Carousel.tsx
> +            // для корректной прокрутки зацикленной карусели к сфокусированному элементу, необходимо получить его реальный индекс
Коммент нужен на английском, это же публичный проект.

2021-11-29 10:00 UTC, jekatigr requested changes

2021-11-29 14:54 UTC, merged