Update colors
MegafonWebLab/megafon-ui pull request #774
Opened 2021-11-26 11:01 UTC by IggyStooges

2021-12-03 16:40 UTC, jekatigr requested changes

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-core/src/components/ContentArea/ContentArea.tsx
> +    FRESH_ASPHALT: 'content',
Ломает обратную совместимость, после выхода из беты нам нужно блюсти стабильность api. 
Нужно добавить еще один вариант цвета CONTENT: 'content'.

И чтобы безболезненно выпилить этот вариант в 3 версии:

- https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#deprecated-support
добавить у этого элемента коммент, тогда внутри проекта либы ide будет подсвечивать, что такой вариант нельзя использовать
- Дополнительно добавить кастомную валидацию в проптайпсах. К сожалению, проекты задают этот пропс в виде строки из-за сложностей экспорта enum-а из либы, поэтому придется изощряться так. В проптайпсах на это поле при значении 'freshAsphalt' нужно выдавать warning, что такое значение устарело и нужно использовать content.

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-core/src/components/Paragraph/Paragraph.tsx
> +    color?: 'green' | 'purple' | 'base' | 'spbSky0' | 'spbSky1' | 'spbSky2' | 'content' | 'fullBlack' | 'inherit';
Тут тоже самое. На уровне демки нужно использовать новый вариант (старый даже не упоминать), но в api обратную совместимость нужно оставить.

Плюс нужно проверить, что в таблице пропсов в демо нет старого варианта, либо для него указано, что он deprecated (в описании поля в таблице хотя бы).

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-core/src/styles/base.less
>  // Notification Colors
По идее, этот мр и есть те самые доработки палитры, значит тут нужны правки.

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-shared/src/components/StoreBanner/StoreBanner.tsx
> +    CLEAR_WHITE: 'base',
И тут.

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-shared/src/components/VideoBanner/doc/VideoBanner.props.mdx
> +    textColor?: 'content' | 'base';
Кажется, это ошибка. Причем в изначальном варианте даже, там другие значения пропертей.

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-core/src/colors/Colors.tsx
> +            <Paragraph>Палитра цветов, используемая в продуктах МегаФон</Paragraph>
От заголовка до параграфа отступ меньше, чем в макете. Это точно моя локальная проблема?

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-core/src/colors/Colors.tsx
> +            <Header as="h1">Colors</Header>
Я бы уточнил, не нужно ли перевести заголовок на русский. А то странно, что пункт в меню слева у нас на русском, а заголовок страницы не совпадает с пунктом меню.

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-core/src/colors/Colors.tsx
> +    const renderBasicsColors = (): JSX.Element => {
```suggestion
    const renderBasicColors = (): JSX.Element => {
```

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-core/src/colors/ColorsItem/ColorsItem.tsx
> +const ColorsItem: React.FC<Props> = ({ colorCode, colorName, parentColorCode, gradient, border, className }) => (
```suggestion
const ColorItem: React.FC<Props> = ({ colorCode, colorName, parentColorCode, gradient, border, className }) => (
```

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-core/src/colors/colorsData.tsx
> +export default {
Было бы круто добавить типизацию этого объекта, чтобы не копаться в огромном файле, чтобы понять структуру.

2021-12-03 16:40 UTC, jekatigr commented on packages/ui-core/src/colors/ColorsItem/ColorsItem.tsx
> +const cn = cnCreate('colors-item');
```suggestion
const cn = cnCreate('color-item');
```

2021-12-03 17:10 UTC, myfka requested changes

2021-12-06 07:01 UTC, IggyStooges commented on packages/ui-core/src/colors/Colors.less
> +        padding: 56px 80px 40px;
Ага, для этого случая нет нужного правила в frontend-presets.

2021-12-06 08:58 UTC, IggyStooges commented on packages/ui-core/src/colors/Colors.tsx
> +            <Header as="h1">Colors</Header>
на уточнении)

2021-12-07 13:06 UTC, jekatigr requested changes

2021-12-08 09:26 UTC, IggyStooges commented on packages/ui-shared/src/components/StoreBanner/StoreBanner.tsx
>      CLEAR_WHITE: 'clearWhite',
нужен, а как же

2021-12-08 12:11 UTC, jekatigr approved these changes

2021-12-13 16:38 UTC, merged