Add accessibility to accordion, checkbox and calendar
MegafonWebLab/megafon-ui pull request #789
Opened 2021-12-14 10:49 UTC by annkuzn

2022-01-20 14:35 UTC, jekatigr requested changes

2022-01-20 14:35 UTC, jekatigr commented on packages/ui-core/src/components/Checkbox/Checkbox.tsx
> +    useEffect(() => {
Эффект бесполезен, он по сути после любого изменения стейта задублирует операцию.

2022-01-20 14:35 UTC, jekatigr commented on packages/ui-core/src/components/Checkbox/Checkbox.tsx
> +            setIsChecked(!isChecked);
Кажется можно не задавать этот стейт, а просто дергать колбэк.

2022-01-20 14:35 UTC, jekatigr commented on packages/ui-core/src/components/Checkbox/Checkbox.tsx
> +    const [isChecked, setIsChecked] = useState(checked);
В текущей реализации пропс checked работает только для инициализации, дальнейшие его изменения будут игнорироваться. Т.е. ранее компонент был контроллируемым, теперь стал неконтролируемым и им уже нельзя управлять извне без перерендера. Кажется лучше обойтись без внутреннего стейта.

2022-01-21 09:26 UTC, annkuzn commented on packages/ui-core/src/components/Checkbox/Checkbox.tsx
> +    useEffect(() => {
Исправила  isChecked на проп checked. Теперь эффект полезен для контролирования состояния чекбокса извне.

2022-01-21 10:47 UTC, jekatigr commented on packages/ui-shared/src/components/AccordionBox/AccordionBox.tsx
> +    onClickAccordion?: (isOpened: boolean) => void;
Это breaking, дожен быть коммит с этим изменением и скоупом accordionBox.

2022-01-21 10:48 UTC, jekatigr commented on packages/ui-core/src/components/Accordion/Accordion.tsx
> +    onClickAccordion?: (isOpened: boolean) => void;
Это breaking, в сообщении коммита должна быть информация об этом. (сам breaking и инструкция по миграции)

2022-01-21 10:49 UTC, jekatigr commented on packages/ui-core/src/components/Checkbox/Checkbox.tsx
> +    onChange?: (checked: boolean) => void;
Тут аналогично, breaking + инструкция по миграции.

2022-01-21 10:52 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/components/Month/Month.tsx
> +    const handleArrowRightClick = (e: AccessibilityEventTypeNative): void => {
Почему-то не отрабатывает для Enter с фокусом на стрелки в демо.

2022-01-21 13:39 UTC, annkuzn commented on packages/ui-core/src/components/Calendar/components/Month/Month.tsx
> +    const handleArrowRightClick = (e: AccessibilityEventTypeNative): void => {
Исправила тип события на AccessibilityEventType.

2022-01-24 10:12 UTC, merged