feat(select): made select as a functional component
MegafonWebLab/megafon-ui pull request #837
Opened 2022-01-28 10:26 UTC by Rakot1234

2022-02-01 14:33 UTC, jekatigr requested changes

2022-02-01 14:33 UTC, jekatigr commented on packages/ui-core/src/components/Select/reducer/selectReducer.ts
> +    activeIndex: 0,
Может переименовать в hoveredItemIndex? А то сейчас постоянно приходится вспоминать, за что он отвечает и почему это не индекс текущего выбранного значения в селекте.

2022-02-01 14:33 UTC, jekatigr commented on packages/ui-core/src/components/Select/reducer/selectReducer.ts
> +    filteredItems: [],
Возможно тоже лучше переименовать, этот список в половине случаев к фильтрации не имеет отношения.

2022-02-01 14:33 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +        isOpened && handleClosed();
Лучше в начале функции определить переменную для нового значения isOpened и использовать ее тут и в событии выше. А то тут логика не совсем прозрачна.

2022-02-03 17:37 UTC, Rakot1234 commented on packages/ui-core/src/components/Select/reducer/selectReducer.ts
> +    comparableInputValue: '',
Оно, просто, переименовывается при дестрктуризации, используется при сравнении значений, по нему идет подсветка частей слов при поиске

2022-02-07 13:33 UTC, jekatigr requested changes

2022-02-07 13:33 UTC, jekatigr commented on packages/ui-core/src/components/Select/reducer/selectReducer.ts
> +        isOpened = false,
Лучше не задавать тут умолчание, но передавать в toggle его в явном виде.
```suggestion
        isOpened,
```

2022-02-07 13:33 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +                type: SET_HOVERED_ITEM_INDEX,
Тут не хватает коммента, для чего нужна эта ветка. Кейс очень специфичный, чтобы понять пришлось сравнивать работку компонента с/без этой обработки.

2022-02-07 13:33 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +    // Used in various handlers instead useEffect with isOpened dependency because on component render isOpened equalse false
```suggestion
    // Used in various handlers instead useEffect with isOpened dependency because on initial component render isOpened is false
```

2022-02-07 13:33 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +// - If value chosen should scroll to chosen element (if scroll required), highlight it with bold and set hovered.
```suggestion
// - Should scroll to chosen element (to make it visible), highlight it with bold and set hovered on dropdown open.
```

2022-02-07 13:33 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +// - While dropdown is opened list should scroll (if required) and highlight next/previous element on arrow up and arrow down presses
```suggestion
// - Should scroll (to make hovered element visible) and highlight next/previous element on arrow up and arrow down presses when dropdown is opened
```

2022-02-07 13:33 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +// Separately required to check simple case and combobox via filtration.
Тут не понятно, что требуется.

2022-02-07 13:33 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +// Its important to check that callback doesn’t call multiple times on outside click if dropdown was opened multiple times.
Возможно так:
```suggestion
// - onClose callback shouldn't fire multiple times on outside click if dropdown was opened multiple times.
```

2022-02-07 14:56 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +        () => () => {
Эту функцию нужно вернуть же.

2022-02-07 15:06 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
>              changeSelectState({
Если вынести изменение этого стейта из под условного блока (т.е. делать его после открытия дропдауна и оставить ранний возврат), то подсветка корректно отрабатывает. Кажется правильнее определять подсвеченный элемент в момент открытия, а не закрытия (может список поменялся уже).

2022-02-08 14:19 UTC, merged