feat(createtestid): added util to form id string for autotest purposes
MegafonWebLab/megafon-ui pull request #885
Opened 2022-03-02 15:37 UTC by Rakot1234

2022-03-02 15:53 UTC, jekatigr requested changes

2022-03-02 15:53 UTC, jekatigr commented on packages/ui-helpers/src/createTestId.ts
> +    const stringPatter = /^[a-zA-Z]+$/;
```suggestion
    const stringPattern = /^[a-zA-Z]+$/;
```
И лучше вынести наверх.

2022-03-02 15:53 UTC, jekatigr commented on packages/ui-helpers/src/createTestId.ts
> +                console.warn(`Wrong element index ${nextArgument}. Index should be above zero and in number format.`);
Думаю в warning'и нужно добавить инфу про контекст, чтобы потом мучительно не выискивать, откуда прилетело, т.е. вывести имя блока и все аргументы.

2022-03-03 11:41 UTC, IGoRFonin commented on packages/ui-helpers/src/createTestId.ts
> +    const stringPatter = /^[a-zA-Z]+$/;
может быть такая ситуация. Вложенность компонентов
`Wrapper -> Carousel -> CarouselItem -> CarouselItemButton`
В CarouselItem передается пропс testId="wrapper-carousel-carouselItem[1]" и внутри он берет этот пропс прогоняет повторно через эту функцию и добавляет button. Так что такой паттерн не подходит.

2022-03-03 11:41 UTC, IGoRFonin commented on packages/ui-helpers/src/createTestId.ts
> +const createTestId = (blockName: string): CreateTestIdType => {
Функцию и файл надо назвать как то по другому, библиотека ничего не должна знать о тестах площадок. Может что-то типо `nestingNameGenerator`

2022-03-10 09:59 UTC, IGoRFonin commented on packages/ui-helpers/src/nestingNameGenerator.ts
> +const nestingNameGenerator = (blockName: string): NestingNameGeneratorReturnType => {
наверное больше для чистоты кода, надо добавить второй аргумент который будет объектом опций. Добавить в него startIndex, который будет числом, если он задан, то он присваивается к переменной index на 15 строке

2022-03-10 09:59 UTC, IGoRFonin commented on packages/ui-helpers/src/nestingNameGenerator.ts
> +const nestingNameGenerator = (blockName: string): NestingNameGeneratorReturnType => {
согласовано

2022-03-14 11:59 UTC, merged