11385 refactor docs demo
MegafonWebLab/megafon-ui pull request #886
Opened 2022-03-04 09:49 UTC by annkuzn

2022-03-05 21:37 UTC, jekatigr requested changes

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Button/doc/Button.example.mdx
>      <Button sizeAll="small" showLoader>Small</Button>
Ниже пример "ссылка на элемент" - думаю его правильно удалить, он не несет вообще никакого смысла для ui (как data-атрибуты или примиксованные классы).

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Calendar/doc/Calendar.example.mdx
> +    <Calendar maxBookingDate={maxBookingDateInCurrentMonth} />
Ниже есть блок "демо-данные", нужно добавить туда maxBookingDateInCurrentMonth

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Carousel/doc/Carousel.example.mdx
> +## Тема с зеленым фоном
```suggestion
## Зеленым фон?
```

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Carousel/doc/Carousel.example.mdx
> +### Отключена возможность прокручивания свайпами
```suggestion
### Без прокручивания свайпом?
```

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Checkbox/Checkbox.tsx
> +    /** Отключает возможность взаимодействия с чекбоксом */
Отключение чекбокса?

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Counter/Counter.tsx
> +    /** Отключает возможность взаимодействия со счетчиком */
Отключение счетчика?

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Counter/doc/Counter.example.mdx
> +Изначально не установлено максимальное значение
```suggestion
Компонент контроллируется родителем. 
```
Изначально не установлено максимальное значение - это не так, ниже задан initialValue

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Grid/doc/Grid.example.mdx
> +
```suggestion
Применяется при изменении размеров окна.
```

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Grid/doc/Grid.example.mdx
> +### Правое
Странный пример. Точно корректно?

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Notification/doc/Notification.example.mdx
> +     Если высота контента меньше высоты иконки, то они выравниваются по центру контентной области.
Кажется тут было специльно мало текста, чтобы текст центрировался.

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Pagination/doc/Pagination.example.mdx
> +## Переполнение списка страниц
может
Скрытие списка страниц
или
Больше 7 страниц

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Pagination/doc/Pagination.example.mdx
Может удалить пример "Интерактивное демо" и все остальные сделать интерактивными? Тогда код DemoWrapper нужно наверх вынести.

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/RadioButton/RadioButton.tsx
> +    /** Отключает возможность взаимодействия с переключателем */
Отключение радио-кнопки?

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Search/Search.tsx
> +    /** Отключает возможность взаимодействия с полем */
Отключение поля ввода?

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Search/doc/Search.example.mdx
>  ```javascript collapse=Код DemoSearchWrapper и DemoSearchCustomItemsWrapper
DemoSearchCustomItemsWrapper использован только в одном примере, лучше туда перенести.

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Select/Select.tsx
> +    /** Отключает возможность взаимодействия с селектом */
Отключение селекта?

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Select/doc/Select.example.mdx
>  <Playground style={flexStyle}>
Тут специально такие отступы снизу от селекта?

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Switcher/Switcher.tsx
> +    /** Отключает возможность взаимодействия с переключателем */
Отключение переключателя?

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Switcher/doc/Switcher.example.mdx
> +## Отключена возможность взаимодействия с переключателем
может
Переключатель отключен

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Switcher/doc/Switcher.example.mdx
> +### Состояние переключателя - "выкл."
```suggestion
### Состояние - "выкл."
```

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Switcher/doc/Switcher.example.mdx
> +### Состояние переключателя - "вкл."
```suggestion
### Состояние - "вкл."
```

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/TextField/TextField.tsx
> +    /** Отключает возможность взаимодействия с полем */
Отключение поля ввода?

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/TextField/doc/TextField.example.mdx
>      <TextField maxLength={10} />
Максимальное количество текста -> Ограничение длины текста?

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-core/src/components/Tile/doc/Tile.example.mdx
> +### При наведении
Все же "тень при наведении". Ну или "интерактивность"

2022-03-05 21:37 UTC, jekatigr commented on packages/ui-shared/src/components/TitleDescriptionBox/doc/TitleDescriptionBox.example.mdx
> +#
Точно правильно добавлять отступы через вставку h1 отдельным пустым компонентом? Может везде в docz добавить отступы для заголовков?

2022-03-16 09:29 UTC, annkuzn commented on packages/ui-core/src/components/Notification/doc/Notification.example.mdx
> +     Если высота контента меньше высоты иконки, то они выравниваются по центру контентной области.
Он по-прежнему центрируется.

2022-03-16 09:31 UTC, annkuzn commented on packages/ui-core/src/components/Pagination/doc/Pagination.example.mdx
> +## Переполнение списка страниц
Заменила на "Частичное скрытие списка страниц"

2022-03-16 09:37 UTC, annkuzn commented on packages/ui-core/src/components/Select/doc/Select.example.mdx
>  <Playground style={flexStyle}>
Смысла больших отступов не увидела, так что изменила.

2022-03-16 09:37 UTC, annkuzn commented on packages/ui-core/src/components/Select/doc/Select.example.mdx
>  <Playground style={flexStyle}>
Смысла больших отступов не увидела, так что изменила.

2022-03-16 10:55 UTC, annkuzn commented on packages/ui-shared/src/components/TitleDescriptionBox/doc/TitleDescriptionBox.example.mdx
> +#
У заголовков уже есть отступы, но не везде их достаточно. Добавила отступы для Playground, лишние вставки h1 убрала.

2022-03-16 12:52 UTC, annkuzn commented on packages/ui-core/src/components/Grid/doc/Grid.example.mdx
> +### Правое
Изменила пример, сделав точно противоположно левому смещению.

2022-03-16 15:41 UTC, jekatigr commented on packages/ui-shared/src/components/CardsBox/doc/CardsBox.example.mdx
> +Если нужен слайдер на всех разрешениях, то необходимо использовать компонет **CarouselBox**.
```suggestion
Если нужен слайдер на всех разрешениях, то необходимо использовать компонент **CarouselBox**.
```

2022-03-16 15:46 UTC, jekatigr commented on packages/ui-core/src/components/Pagination/doc/Pagination.example.mdx
> +    <DemoWrapper totalPages={7} activePage={1} />
Тут странный паттерн для отображения примеров. Лучше сделать также, как в других компонентах (например Counter).

2022-03-16 15:47 UTC, jekatigr commented on packages/ui-core/src/components/Pagination/doc/Pagination.example.mdx
> +    <DemoWrapper totalPages={7} activePage={1} />
Тут странный паттерн для отображения примеров. Лучше сделать также, как в других компонентах (например Counter).

2022-03-21 11:43 UTC, merged