Typography components
MegafonWebLab/megafon-ui pull request #922
Opened 2022-04-21 12:32 UTC by svetogor

### ui-core

- `Paragraph`: remove prop `size`; add prop `space`; add to `color` prop option `gray`; change basic styles
- `Caption`: new typography component
- `base.less`: change mixins `.commonFont()` and `.smallFont()`
- `docs`: update docs for `Paragraph`; add docs for `Caption`

2022-04-21 20:50 UTC, jekatigr requested changes

2022-04-21 20:50 UTC, jekatigr commented on packages/ui-core/src/components/Caption/Caption.less
> +@import (reference) '~styles/base.less';
prop 'size' is no longer exists -> prop 'size' is no longer exists, use Caption component instead

Смысл в том, чтобы по breaking-change-notes составлять инструкцию по миграции.

2022-04-21 20:50 UTC, jekatigr commented on packages/ui-core/src/components/Caption/Caption.less
> +
fix(paragraph): rename prop room to space; add pale to color prop values

prop room rename to space; prop color now has new variant: pale

BREAKING CHANGE: prop room rename to space; prop color now has new variant: pale

---

пропс room не существовал в целевой ветке, в changelog бессмысленно писать о переименовании того, что еще не существовало в публичном api. Тут можно либо переписать содержимое изначального коммита про добавление пропса (и сообщение в нем), либо (что менее правильно) изменить message изначального коммита на скоуп, который не попадет в chagelog (refactor например), а в коммите с переименованием в message писать, что был добавлен пропс. Тогда будет корректный changelog.

2022-04-21 20:50 UTC, jekatigr commented on packages/ui-core/src/components/Caption/Caption.less
> +@b: e('.mfui-caption');
Ну и последующие коммиты с фиксами 'pale' to 'gray' тоже по той же схеме.

2022-04-21 20:50 UTC, jekatigr commented on packages/ui-core/src/components/Paragraph/Paragraph.tsx
> +    /** Встраивание в широкий или узкий контейнер */
```suggestion
    /** Поведение текста при встраивании в широкий или узкий контейнер */
```

2022-04-21 20:50 UTC, jekatigr commented on packages/ui-core/src/components/Caption/Caption.tsx
> +    /** Встраивание в широкий или узкий контейнер */
```suggestion
    /** Поведение текста при встраивании в широкий или узкий контейнер */
```

2022-04-21 20:50 UTC, jekatigr commented on packages/ui-core/src/components/Caption/Caption.test.tsx
> +    it('render with align prop', () => {
По идее, передачей всех вариантов всех пропсов никогда не занимались, потому что два верхних теста уже дают полное покрытие. Внутри компонента нет никакой логики, завязанной на пропсы, все они передаются в рендер. Первый тест рендерит компонент по умолчанию, второй задает все пропсы и фиксирует, что они попали в нужное место в верстке. Если бы там была какая-то дополнительная логика, связанная с пропсами, то потребовались бы дополнительные тесты, но в данном случае фиксировать все варианты излишне. К параграфу тоже относится.

2022-04-21 20:50 UTC, jekatigr commented on packages/ui-core/src/components/Caption/doc/Caption.example.mdx
> +            Короткий кэпшн для узкого контейнера
Возможно, "узкий для узкого"?

2022-04-21 23:10 UTC, jekatigr commented on packages/ui-core/src/components/Caption/Caption.less
> +
И пр должен быть направлен в ветку beta.

2022-05-18 11:42 UTC, svetogor commented on packages/ui-core/src/components/Caption/Caption.less
> +@import (reference) '~styles/base.less';
исправил

2022-05-18 11:42 UTC, svetogor commented on packages/ui-core/src/components/Caption/Caption.less
> +
готово

2022-05-18 11:42 UTC, svetogor commented on packages/ui-core/src/components/Caption/Caption.less
> +@b: e('.mfui-caption');
сделал

2022-05-18 11:42 UTC, svetogor commented on packages/ui-core/src/components/Caption/Caption.test.tsx
> +    it('render with align prop', () => {
убрал лишние тесты

2022-05-18 11:42 UTC, svetogor commented on packages/ui-core/src/components/Caption/Caption.less
> +
направил

2022-05-24 11:19 UTC, merged